import {extractMaterialAttributes} from './normalize';
import {matchMaterials,scoreMaterialCandidate,validateMaterialMatchIntegrity} from './matcher';
import {groupAmounts,unitChanged} from './groups';
import type {ComparisonState,MaterialMatchCluster} from './types';
const counts=(cs:MaterialMatchCluster[])=>({referenceOnly:cs.filter(c=>c.referenceRowIds.length&&!c.currentRowId).length,comparisonOnly:cs.filter(c=>!c.referenceRowIds.length&&c.currentRowId).length,needsReview:cs.filter(c=>c.status==='REVIEW').length});
export function auditComparison(state:ComparisonState){return state.styleMatches.filter(s=>!s.excluded).map(s=>{
 const reference=state.styles.find(x=>x.id===s.referenceId),comparison=state.styles.find(x=>x.id===s.currentId),refs=reference?.materials||[],curr= comparison?.materials||[],before=state.materialMatches.find(x=>x.styleMatchId===s.id),after=matchMaterials(s,state.styles,before),totals=groupAmounts(after.clusters,refs,curr),integrity=validateMaterialMatchIntegrity(refs,curr,after.clusters);
 const unresolved=after.clusters.filter(c=>!c.currentRowId||!c.referenceRowIds.length||c.status==='REVIEW');
 return {style:comparison?.styleName||reference?.styleName,before:counts(before?.clusters||[]),after:counts(after.clusters),totals,integrity,sourceSummary:{reference:reference?.summary.totalMaterialCost,comparison:comparison?.summary.totalMaterialCost},summaryMatches:{reference:reference?.summary.totalMaterialCost===undefined?null:Math.abs(integrity.referenceTotal-reference.summary.totalMaterialCost)<.0001,comparison:comparison?.summary.totalMaterialCost===undefined?null:Math.abs(integrity.comparisonTotal-comparison.summary.totalMaterialCost)<.0001},newMatches:after.clusters.filter(c=>c.currentRowId&&c.referenceRowIds.length&&!before?.clusters.some(b=>b.currentRowId===c.currentRowId&&b.referenceRowIds.join()===c.referenceRowIds.join())),unitChanged:after.clusters.filter(c=>unitChanged(refs.filter(r=>c.referenceRowIds.includes(r.id)),curr.find(r=>r.id===c.currentRowId))),groupChanged:after.clusters.filter(c=>c.referenceOriginalGroup&&c.referenceOriginalGroup!==c.effectiveGroup),manyToOne:after.clusters.filter(c=>c.relationType==='many-to-one'),unresolved:unresolved.map(c=>{const r=refs.find(r=>c.referenceRowIds.includes(r.id)),current=curr.find(r=>r.id===c.currentRowId);const candidates=(r?curr.map(x=>({row:x,score:scoreMaterialCandidate(r,x)})):current?refs.map(x=>({row:x,score:scoreMaterialCandidate(x,current)})):[]).sort((a,b)=>b.score.score-a.score.score);return{group:c.effectiveGroup,row:r||current,attributes:extractMaterialAttributes((r||current)?.material||''),topThree:candidates.slice(0,3),margin:(candidates[0]?.score.score??0)-(candidates[1]?.score.score??0),reason:candidates[0]?.score.blocked||((candidates[0]?.score.score??0)<90?'Below identity threshold':'Candidate competition or margin below 8')}})};
 });}
