import {useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowLeft,Download,FileSpreadsheet,GitCompareArrows,Redo2,RotateCcw,Undo2,Upload} from 'lucide-react';
import {exportComparison} from './exporter';
import {matchMaterials,matchStyles} from './matcher';
import {parseCbdFiles} from './parser';
import {clearComparison,loadComparison,saveComparison} from './persistence';
import './cluster.css';
import type {CbdMaterialRow,CbdStyle,ComparisonSide,ComparisonState,MaterialMatchCluster,StyleMatch} from './types';

const initialState:ComparisonState={version:2,referenceSeason:'27',currentSeason:'28',files:[],styles:[],styleMatches:[],materialMatches:[],step:1};
const groupNames=['OUTSHELL','TRIMS','SEWING THREAD','LABEL & PACKAGING'];
const stepLabels=['Upload CBD Files','Match Styles','Review Material Matches','Comparison Preview','Export Comparison'];
type MaterialFilter='all'|'changed'|'referenceOnly'|'comparisonOnly'|'needsReview'|`group:${string}`;
const money=(value?:number)=>value===undefined?'':`$${value.toFixed(4)}`;
const difference=(reference?:number,comparison?:number)=>reference===undefined||comparison===undefined?undefined:comparison-reference;
const getRow=(style:CbdStyle|undefined,id?:string)=>style?.materials.find(row=>row.id===id);
const sumRows=(style:CbdStyle|undefined,ids:string[],key:'cost'|'usage'|'extended')=>{const values=ids.map(id=>getRow(style,id)?.[key]).filter((value):value is number=>value!==undefined);return values.length?values.reduce((a,b)=>a+b,0):undefined};
const displayStatus=(status:string)=>status==='current-only'||status==='CURRENT ONLY'?'Comparison Only':status==='reference-only'||status==='REFERENCE ONLY'?'Reference Only':status==='review'||status==='REVIEW'?'Needs Review':status==='duplicate'?'Duplicate — Needs Review':status;

export default function ComparisonWorkspace({onBack}:{onBack:()=>void}){
 const [state,setState]=useState(initialState),[past,setPast]=useState<ComparisonState[]>([]),[future,setFuture]=useState<ComparisonState[]>([]);
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[restoring,setRestoring]=useState(true),[materialFilter,setMaterialFilter]=useState<MaterialFilter>('all'),[sort,setSort]=useState('order');
 const [pending,setPending]=useState<{setId:string;clusterId:string;currentId:string}|null>(null),hydrated=useRef(false);
 useEffect(()=>{loadComparison().then(saved=>{if(saved){setState(saved);setPast(saved.history?.past||[]);setFuture(saved.history?.future||[])}}).catch(()=>setNotice('The saved comparison could not be restored.')).finally(()=>{hydrated.current=true;setRestoring(false)})},[]);
 useEffect(()=>{if(!hydrated.current)return;const timer=setTimeout(()=>saveComparison({...state,history:{past:past.slice(-20),future:future.slice(0,20)}}).catch(()=>setNotice('Automatic saving failed.')),400);return()=>clearTimeout(timer)},[state,past,future]);
 const mutate=(fn:(old:ComparisonState)=>ComparisonState)=>setState(old=>{setPast(items=>[...items,structuredClone(old)].slice(-20));setFuture([]);return fn(old)});
 const undo=()=>{const previous=past.at(-1);if(!previous)return;setFuture(items=>[structuredClone(state),...items].slice(0,20));setPast(items=>items.slice(0,-1));setState({...structuredClone(previous),activeMatchId:state.activeMatchId,step:state.step})};
 const redo=()=>{const next=future[0];if(!next)return;setPast(items=>[...items,structuredClone(state)].slice(-20));setFuture(items=>items.slice(1));setState({...structuredClone(next),activeMatchId:state.activeMatchId,step:state.step})};
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey)||['INPUT','TEXTAREA','SELECT'].includes((event.target as HTMLElement)?.tagName))return;if(event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo()}else if(event.key.toLowerCase()==='y'){event.preventDefault();redo()}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[state,past,future]);
 const upload=async(side:ComparisonSide,files:File[])=>{const valid=files.filter(file=>/\.xlsx?$/i.test(file.name));if(!valid.length){setNotice('Select .xls or .xlsx files.');return}setBusy(true);try{const result=await parseCbdFiles(valid,side);mutate(old=>{const styles=[...old.styles,...result.styles],styleMatches=styles.some(s=>s.side==='reference')&&styles.some(s=>s.side==='current')?matchStyles(styles):[];return{...old,styles,files:[...old.files,...result.files],styleMatches,materialMatches:[],step:styleMatches.length?2:1}});setNotice(`${side==='reference'?'Reference':'Comparison'} Season: ${result.files.length} ${result.files.length===1?'file':'files'} · ${result.styles.length} ${result.styles.length===1?'style':'styles'}${result.errors.length?` · ${result.errors.join(' ')}`:''}`)}finally{setBusy(false)}};
 const style=(id?:string)=>state.styles.find(item=>item.id===id),active=state.styleMatches.find(match=>match.id===state.activeMatchId)||state.styleMatches.find(match=>!match.excluded),reference=style(active?.referenceId),comparison=style(active?.currentId),matchSet=state.materialMatches.find(item=>item.styleMatchId===active?.id)||{styleMatchId:'',clusters:[]};
 const updateStyle=(id:string,patch:Partial<StyleMatch>)=>mutate(old=>({...old,styleMatches:old.styleMatches.map(match=>match.id===id?{...match,...patch}:match)}));
 const setAllExcluded=(excluded:boolean)=>mutate(old=>({...old,styleMatches:old.styleMatches.map(match=>({...match,excluded}))}));
 const confirmStyles=()=>{if(state.styleMatches.every(match=>match.excluded)){setNotice('No styles are selected for comparison.');return}const unresolved=state.styleMatches.filter(match=>!match.excluded&&(match.status==='review'||match.status==='duplicate'));if(unresolved.length){setNotice(`Resolve ${unresolved.length} style ${unresolved.length===1?'match':'matches'} before continuing.`);return}mutate(old=>({...old,materialMatches:old.styleMatches.filter(match=>!match.excluded).map(match=>{const existing=old.materialMatches.find(set=>set.styleMatchId===match.id);return existing||matchMaterials(match,old.styles)}),step:3,activeMatchId:old.activeMatchId||old.styleMatches.find(match=>!match.excluded)?.id}))};
 const runExport=()=>{if(!state.styleMatches.length){goToStep(5);return}if(state.styleMatches.every(match=>match.excluded)){setNotice('No styles are selected for comparison.');return}if(!state.materialMatches.length){setNotice('Resolve or confirm material matches before export.');setState(old=>({...old,step:old.styleMatches.length?2:1}));return}void exportComparison(state)};
 const goToStep=(step:1|2|3|4|5)=>{const hasReference=state.styles.some(s=>s.side==='reference'),hasComparison=state.styles.some(s=>s.side==='current');if(step>1&&(!hasReference||!hasComparison)){setNotice('Upload both Reference and Comparison CBD files first.');setState(old=>({...old,step:1}));return}if(step>2&&!state.materialMatches.length){setNotice('Confirm Style Matches before reviewing materials.');setState(old=>({...old,step:2}));return}if(step===5&&state.styleMatches.every(match=>match.excluded)){setNotice('No styles are selected for comparison.');setState(old=>({...old,step:2}));return}setState(old=>({...old,step}))};
 const applyLink=(setId:string,clusterId:string,currentId:string|null,mode:'link'|'merge'|'move'='link')=>mutate(old=>({...old,materialMatches:old.materialMatches.map(set=>{if(set.styleMatchId!==setId)return set;let clusters=set.clusters.map(cluster=>({...cluster,referenceRowIds:[...cluster.referenceRowIds]}));const target=clusters.find(cluster=>cluster.id===clusterId);if(!target)return set;if(mode==='merge'&&currentId){const owner=clusters.find(cluster=>cluster.id!==clusterId&&cluster.currentRowId===currentId);if(owner){owner.referenceRowIds.push(...target.referenceRowIds);owner.relationType='many-to-one';owner.matchSource='manual';owner.status='MERGED N:1';clusters=clusters.filter(cluster=>cluster.id!==target.id)}}else{if(currentId)clusters=clusters.filter(cluster=>cluster.id===target.id||cluster.currentRowId!==currentId||cluster.referenceRowIds.length>0);if(mode==='move'&&currentId){const owner=clusters.find(cluster=>cluster.id!==clusterId&&cluster.currentRowId===currentId);if(owner){owner.currentRowId=null;owner.status='REFERENCE ONLY';owner.relationType='one-to-one';owner.matchSource='manual'}}target.currentRowId=currentId;target.relationType='one-to-one';target.matchSource='manual';target.status=currentId?'MANUAL':'REFERENCE ONLY';const row=getRow(comparison,currentId||undefined);if(row)target.finalGroup=row.group}return{...set,clusters}})}));
 const choose=(cluster:MaterialMatchCluster,currentId:string|null)=>{if(!currentId){applyLink(matchSet.styleMatchId,cluster.id,null);setNotice('The Comparison Material was unlinked.')}else if(matchSet.clusters.some(item=>item.id!==cluster.id&&item.currentRowId===currentId&&item.referenceRowIds.length>0))setPending({setId:matchSet.styleMatchId,clusterId:cluster.id,currentId});else{applyLink(matchSet.styleMatchId,cluster.id,currentId);setNotice('Comparison Material linked.')}};
 const changeGroup=(clusterId:string,finalGroup:string)=>mutate(old=>({...old,materialMatches:old.materialMatches.map(item=>item.styleMatchId===matchSet.styleMatchId?{...item,clusters:item.clusters.map(cluster=>cluster.id===clusterId?{...cluster,finalGroup,matchSource:'manual'}:cluster)}:item)}));
 const availableGroups=useMemo(()=>[...new Set([...matchSet.clusters.map(cluster=>cluster.finalGroup),...(reference?.materials||[]).map(row=>row.group),...(comparison?.materials||[]).map(row=>row.group)])].filter(Boolean),[matchSet,reference,comparison]);
 const visible=useMemo(()=>{const metric=(cluster:MaterialMatchCluster,key:'cost'|'usage'|'extended')=>Math.abs(difference(sumRows(reference,cluster.referenceRowIds,key),getRow(comparison,cluster.currentRowId||undefined)?.[key])||0),changed=(cluster:MaterialMatchCluster)=>{if(!cluster.referenceRowIds.length||!cluster.currentRowId)return false;const refs=cluster.referenceRowIds.map(id=>getRow(reference,id)).filter(Boolean) as CbdMaterialRow[],current=getRow(comparison,cluster.currentRowId);if(!current)return false;return refs.map(row=>row.material).join(' + ')!==current.material||refs.some(row=>row.group!==cluster.finalGroup)||new Set(refs.map(row=>row.unit)).size!==1||refs[0]?.unit!==current.unit||(['cost','usage','extended'] as const).some(key=>Math.abs((sumRows(reference,cluster.referenceRowIds,key)||0)-(current[key]||0))>.00005)};const include=(cluster:MaterialMatchCluster)=>materialFilter==='all'||materialFilter==='changed'&&changed(cluster)||materialFilter==='referenceOnly'&&cluster.referenceRowIds.length>0&&!cluster.currentRowId||materialFilter==='comparisonOnly'&&cluster.referenceRowIds.length===0&&!!cluster.currentRowId||materialFilter==='needsReview'&&cluster.status==='REVIEW'||materialFilter.startsWith('group:')&&cluster.finalGroup===materialFilter.slice(6);return matchSet.clusters.filter(include).sort((a,b)=>sort==='order'?(getRow(comparison,a.currentRowId||undefined)?.order??9999)-(getRow(comparison,b.currentRowId||undefined)?.order??9999):metric(b,sort as 'cost')-metric(a,sort as 'cost'))},[matchSet,materialFilter,sort,reference,comparison]);
 if(restoring)return <main className="comparison-loading">Loading CBD Comparison…</main>;
 const comparisonContent=<><GroupComparison reference={reference} comparison={comparison} clusters={matchSet.clusters} referenceSeason={state.referenceSeason} comparisonSeason={state.currentSeason}/><MaterialTable clusters={state.step===3?visible:matchSet.clusters} reference={reference} comparison={comparison} editable={state.step===3} onChange={choose} onGroup={changeGroup}/>{state.step===3&&<Additional comparison={comparison} clusters={matchSet.clusters}/>}</>;
 return <div className="comparison-app"><Sidebar state={state} onBack={onBack} onStep={goToStep} onClear={async()=>{if(window.confirm('Reset the CBD Comparison workspace?')){await clearComparison();setState(initialState);setPast([]);setFuture([])}}}/><main className="comparison-workspace"><header><div><span className="eyebrow">Internal Cost Review · {state.currentSeason} – {state.referenceSeason}</span><h1>CBD Comparison</h1><p>Internal cost review of group-level material cost differences and item-level Cost per Unit, Usage, and Extended Cost changes.</p></div></header>{notice&&<div className="notice bar">{notice}<button type="button" aria-label="Dismiss" onClick={()=>setNotice('')}>×</button></div>}{state.step===1&&<section className="comparison-upload-grid"><UploadBox side="reference" title={`Reference Season ${state.referenceSeason}`} season={state.referenceSeason} onSeason={value=>mutate(old=>({...old,referenceSeason:value}))} onFiles={upload} files={state.files.filter(file=>file.side==='reference')} count={state.styles.filter(item=>item.side==='reference').length} busy={busy}/><UploadBox side="current" title={`Comparison Season ${state.currentSeason}`} season={state.currentSeason} onSeason={value=>mutate(old=>({...old,currentSeason:value}))} onFiles={upload} files={state.files.filter(file=>file.side==='current')} count={state.styles.filter(item=>item.side==='current').length} busy={busy}/></section>}{state.step===2&&<StyleMatching matches={state.styleMatches} styles={state.styles} onUpdate={updateStyle} onAll={setAllExcluded} onConfirm={confirmStyles}/>} {(state.step===3||state.step===4)&&<section className="comparison-panel material-review"><MaterialHeading state={state} active={active} style={style} reference={reference} comparison={comparison} onActive={id=>setState(old=>({...old,activeMatchId:id}))}/>{state.step===3&&<MatchingToolbar materialFilter={materialFilter} onFilter={value=>setMaterialFilter(value as MaterialFilter)} groups={availableGroups} sort={sort} onSort={setSort} past={past.length} future={future.length} onUndo={undo} onRedo={redo} onExport={runExport}/>} {comparisonContent}</section>}{state.step===5&&<ExportPreview state={state} reference={reference} comparison={comparison} clusters={matchSet.clusters} onExport={runExport}/>} {pending&&<ConflictDialog onChoice={choice=>{if(choice!=='cancel'){applyLink(pending.setId,pending.clusterId,pending.currentId,choice);setNotice('Comparison Material linked.')}setPending(null)}}/>}</main></div>
}

function Sidebar({state,onBack,onStep,onClear}:{state:ComparisonState;onBack:()=>void;onStep:(step:1|2|3|4|5)=>void;onClear:()=>void}){return <aside><div className="brand small"><span className="brand-mark">CB</span><span className="brand-copy"><b>CBD Manager</b><small>Cost Management</small></span></div><nav className="main-nav"><button type="button" onClick={onBack}><ArrowLeft size={17}/> BOM Management</button><button type="button" className="active"><GitCompareArrows size={17}/> CBD Comparison</button></nav><ol className="comparison-steps">{stepLabels.map((label,index)=><li className={state.step===index+1?'active':state.step>index+1?'done':''} key={label}><button type="button" aria-current={state.step===index+1?'step':undefined} onClick={()=>onStep((index+1) as 1|2|3|4|5)}>{index+1}. {label}</button></li>)}</ol><button type="button" className="comparison-clear" onClick={onClear}><RotateCcw size={15}/> Reset Comparison</button></aside>}
function MaterialHeading({state,active,style,reference,comparison,onActive}:{state:ComparisonState;active?:StyleMatch;style:(id?:string)=>CbdStyle|undefined;reference?:CbdStyle;comparison?:CbdStyle;onActive:(id:string)=>void}){return <div className="comparison-material-head"><div><h2>{state.step===4?'Comparison Preview':'Review Material Matches'}</h2><p><span className="season-fixed">Reference Season {state.referenceSeason} – {reference?.styleName||'None'} (Material fixed)</span> <span className="season-current">Comparison Season {state.currentSeason} – {comparison?.styleName||'None'} (match can be changed)</span></p></div><select aria-label="Selected style comparison" value={active?.id||''} onChange={event=>onActive(event.target.value)}>{state.styleMatches.filter(match=>!match.excluded).map(match=><option value={match.id} key={match.id}>{style(match.referenceId)?.styleName||'None'} ↔ {style(match.currentId)?.styleName||'None'}</option>)}</select></div>}
function MatchingToolbar({materialFilter,onFilter,groups,sort,onSort,past,future,onUndo,onRedo,onExport}:{materialFilter:string;onFilter:(value:string)=>void;groups:string[];sort:string;onSort:(value:string)=>void;past:number;future:number;onUndo:()=>void;onRedo:()=>void;onExport:()=>void}){return <div className="matching-toolbar"><div className="comparison-filters"><label>Materials <select aria-label="Material Filter" value={materialFilter} onChange={event=>onFilter(event.target.value)}><option value="all">All Materials</option><option value="changed">Changed Materials Only</option><option value="referenceOnly">Reference Season Only</option><option value="comparisonOnly">Comparison Season Only</option><option value="needsReview">Needs Review</option>{groups.map(group=><option value={`group:${group}`} key={group}>{group}</option>)}</select></label><label>Sort By <select value={sort} onChange={event=>onSort(event.target.value)}><option value="order">Comparison Season Order</option><option value="cost">Largest Cost Difference</option><option value="usage">Largest Usage Difference</option><option value="extended">Largest Extended Cost Difference</option></select></label></div><div className="comparison-actions"><button type="button" disabled={!past} onClick={onUndo}><Undo2 size={16}/> Undo</button><button type="button" disabled={!future} onClick={onRedo}><Redo2 size={16}/> Redo</button><button type="button" className="primary" onClick={onExport}><Download size={16}/> Export Comparison</button></div></div>}
function StyleMatching({matches,styles,onUpdate,onAll,onConfirm}:{matches:StyleMatch[];styles:CbdStyle[];onUpdate:(id:string,p:Partial<StyleMatch>)=>void;onAll:(excluded:boolean)=>void;onConfirm:()=>void}){const master=useRef<HTMLInputElement>(null),all=matches.length>0&&matches.every(match=>match.excluded),some=matches.some(match=>match.excluded);useEffect(()=>{if(master.current)master.current.indeterminate=some&&!all},[some,all]);return <section className="comparison-panel"><h2>Review Style Matches</h2><p>Reference Styles are fixed. Only Comparison Styles can be changed.</p><div className="comparison-table"><table><thead><tr><th>Reference Style</th><th>Comparison Style</th><th>Match Type</th><th>Confidence</th><th>Status</th><th>Change Comparison Match</th><th><label className="exclude-master"><input ref={master} type="checkbox" checked={all} title={all?'Clear All Exclusions':'Exclude All'} onChange={()=>onAll(!all)}/>{all?'Clear All Exclusions':'Exclude All'}</label></th></tr></thead><tbody>{matches.map(match=>{const reference=styles.find(style=>style.id===match.referenceId),comparison=styles.find(style=>style.id===match.currentId);return <tr className={match.status==='review'||match.status==='duplicate'?'comparison-review':''} key={match.id}><td>{reference?`${reference.fileName} · ${reference.sheetName} · ${reference.styleName}`:'—'}</td><td>{comparison?`${comparison.fileName} · ${comparison.sheetName} · ${comparison.styleName}`:'—'}</td><td>{match.method}</td><td>{Math.round(match.confidence*100)}%</td><td>{displayStatus(match.status)}</td><td><select value={match.currentId||''} onChange={event=>onUpdate(match.id,{currentId:event.target.value||undefined,status:event.target.value?'Manual':'reference-only',method:event.target.value?'Manual':'Unmatched',confidence:event.target.value?1:0})}><option value="">Unlink</option>{styles.filter(style=>style.side==='current').map(style=><option value={style.id} key={style.id}>{style.styleName}</option>)}</select></td><td><input aria-label={`Exclude ${reference?.styleName||'style'}`} type="checkbox" checked={!!match.excluded} onChange={event=>onUpdate(match.id,{excluded:event.target.checked})}/></td></tr>})}</tbody></table></div><button type="button" className="primary" onClick={onConfirm}>Confirm Style Matches</button></section>}
function MaterialTable({clusters,reference,comparison,editable,onChange,onGroup}:{clusters:MaterialMatchCluster[];reference?:CbdStyle;comparison?:CbdStyle;editable:boolean;onChange:(cluster:MaterialMatchCluster,id:string|null)=>void;onGroup:(id:string,group:string)=>void}){return <div className="comparison-table material-table"><table><thead><tr><th>Final Group</th><th className="reference-head">Reference Material – Fixed</th><th className="current-head">Comparison Material {editable?'– Change Match':''}</th><th>Unit</th><th>Reference Cost</th><th>Comparison Cost</th><th className="delta-head">Cost Difference</th><th>Reference Usage</th><th>Comparison Usage</th><th className="delta-head">Usage Difference</th><th>Reference Extended</th><th>Comparison Extended</th><th className="delta-head">Extended Difference</th><th>Status</th></tr></thead><tbody>{clusters.map(cluster=><MaterialRow key={cluster.id} cluster={cluster} references={cluster.referenceRowIds.map(id=>getRow(reference,id)).filter(Boolean) as CbdMaterialRow[]} comparison={getRow(comparison,cluster.currentRowId||undefined)} candidates={comparison?.materials||[]} editable={editable} onChange={id=>onChange(cluster,id)} onGroup={group=>onGroup(cluster.id,group)}/>)}</tbody></table></div>}
function MaterialRow({cluster,references,comparison,candidates,editable,onChange,onGroup}:{cluster:MaterialMatchCluster;references:CbdMaterialRow[];comparison?:CbdMaterialRow;candidates:CbdMaterialRow[];editable:boolean;onChange:(id:string|null)=>void;onGroup:(group:string)=>void}){const total=(key:'cost'|'usage'|'extended')=>{const values=references.map(row=>row[key]).filter((value):value is number=>value!==undefined);return values.length?values.reduce((a,b)=>a+b,0):undefined},number=(value?:number)=>value===undefined?'':value.toFixed(4),delta=(a?:number,b?:number)=>{if(a===undefined&&b===undefined)return '–';const value=(b||0)-(a||0);return Math.abs(value)<.00005?'–':`${value>0?'+':''}${value.toFixed(4)}`},color=(a?:number,b?:number)=>{const value=(b||0)-(a||0);return value>0?'increase':value<0?'decrease':''};return <tr className={`material-status-${cluster.status.toLowerCase().replace(/[: ]/g,'-')}`}><td>{editable?<select aria-label="Final Group" value={cluster.finalGroup} onChange={event=>onGroup(event.target.value)}>{[...new Set([...groupNames,cluster.finalGroup])].map(group=><option key={group} value={group}>{group}</option>)}</select>:cluster.finalGroup}</td><td className="reference-material">{references.length?references.map(row=><span className="material-name" key={row.id}>{row.material}</span>):'—'}</td><td className="current-material">{editable?<select value={cluster.currentRowId||''} onChange={event=>onChange(event.target.value||null)}><option value="">Unlink</option>{candidates.map(row=><option value={row.id} key={row.id}>{`[${row.group}] ${row.material}`}</option>)}</select>:comparison?.material||'—'}{editable&&comparison&&<span className="material-name">{comparison.material}</span>}</td><td>{comparison?.unit||references[0]?.unit||''}</td>{(['cost','usage','extended'] as const).flatMap(key=>{const a=total(key),b=comparison?.[key];return [<td key={key+'a'}>{key==='extended'?money(a):number(a)}</td>,<td key={key+'b'}>{key==='extended'?money(b):number(b)}</td>,<td key={key+'d'} className={`delta ${color(a,b)}`}>{delta(a,b)}</td>]})}<td>{displayStatus(cluster.status)}</td></tr>}
function Additional({comparison,clusters}:{comparison?:CbdStyle;clusters:MaterialMatchCluster[]}){const linked=new Set(clusters.map(cluster=>cluster.currentRowId).filter(Boolean)),rows=(comparison?.materials||[]).filter(row=>!linked.has(row.id));if(!rows.length)return null;return <div className="additional-materials"><h3>Comparison Only Materials</h3><table><thead><tr><th>Final Group</th><th>Comparison Material</th><th>Unit</th><th>Cost per Unit</th><th>Usage</th><th>Extended Cost</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.group}</td><td>{row.material}</td><td>{row.unit}</td><td>{money(row.cost)}</td><td>{row.usage?.toFixed(4)||''}</td><td>{money(row.extended)}</td><td>Comparison Only</td></tr>)}</tbody></table></div>}
function mappedAmount(style:CbdStyle|undefined,clusters:MaterialMatchCluster[],group:string,side:'reference'|'comparison'){const ids=new Set<string>();clusters.filter(cluster=>cluster.finalGroup.toUpperCase()===group).forEach(cluster=>side==='reference'?cluster.referenceRowIds.forEach(id=>ids.add(id)):cluster.currentRowId&&ids.add(cluster.currentRowId));const values=[...ids].map(id=>getRow(style,id)?.extended).filter((value):value is number=>value!==undefined);return values.length?values.reduce((a,b)=>a+b,0):undefined}
function GroupComparison({reference,comparison,clusters,referenceSeason,comparisonSeason}:{reference?:CbdStyle;comparison?:CbdStyle;clusters:MaterialMatchCluster[];referenceSeason:string;comparisonSeason:string}){return <section className="group-comparison"><h2>Material Cost Comparison by Group · {comparison?.styleName||reference?.styleName}</h2><table><thead><tr><th>CBD Group</th><th>Reference Season {referenceSeason}</th><th>Comparison Season {comparisonSeason}</th><th>Difference</th><th>Change %</th></tr></thead><tbody>{[...groupNames,'TOTAL MATERIAL COST'].map(group=>{const a=group==='TOTAL MATERIAL COST'?reference?.summary.totalMaterialCost:mappedAmount(reference,clusters,group,'reference'),b=group==='TOTAL MATERIAL COST'?comparison?.summary.totalMaterialCost:mappedAmount(comparison,clusters,group,'comparison'),d=difference(a,b),p=a&&b!==undefined?d!/a:undefined;return <tr key={group}><td>{group}</td><td>{money(a)}</td><td>{money(b)}</td><td className={d===undefined?'':d>0?'increase':'decrease'}>{d===undefined||Math.abs(d)<.00005?'–':money(d)}</td><td>{p===undefined?'–':`${p>0?'+':''}${(p*100).toFixed(1)}%`}</td></tr>})}</tbody></table></section>}
function ExportPreview({state,reference,comparison,clusters,onExport}:{state:ComparisonState;reference?:CbdStyle;comparison?:CbdStyle;clusters:MaterialMatchCluster[];onExport:()=>void}){return <section className="comparison-panel export-preview"><h2>Export Comparison</h2><p>Review the selected comparison before generating the Excel workbook.</p><GroupComparison reference={reference} comparison={comparison} clusters={clusters} referenceSeason={state.referenceSeason} comparisonSeason={state.currentSeason}/><button type="button" className="primary" onClick={onExport}><Download size={16}/> Export Comparison</button></section>}
function ConflictDialog({onChoice}:{onChoice:(choice:'merge'|'move'|'cancel')=>void}){return <div className="match-dialog-backdrop"><div className="match-dialog" role="dialog" aria-modal="true"><h3>This Comparison Material is already linked to another Reference Material.</h3><p>Would you like to combine both Reference Materials into one merged comparison group?</p><div><button type="button" className="primary" onClick={()=>onChoice('merge')}>Merge Matches</button><button type="button" onClick={()=>onChoice('move')}>Move Existing Match</button><button type="button" onClick={()=>onChoice('cancel')}>Cancel</button></div></div></div>}
function UploadBox({side,title,season,onSeason,onFiles,files,count,busy}:{side:ComparisonSide;title:string;season:string;onSeason:(value:string)=>void;onFiles:(side:ComparisonSide,files:File[])=>void;files:{id:string;name:string}[];count:number;busy:boolean}){const input=useRef<HTMLInputElement>(null),drop=(list:FileList|null)=>list&&onFiles(side,[...list]);return <section className={`comparison-upload ${side}`}><div><FileSpreadsheet/><h2>{title}</h2><p>{side==='reference'?'Previous season · Source Material is fixed':'Latest season · Basis for Group, order, and matching'}</p></div><label>Season<input value={season} onChange={event=>onSeason(event.target.value)}/></label><button type="button" disabled={busy} onClick={()=>{if(input.current)input.current.value='';input.current?.click()}} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();drop(event.dataTransfer.files)}}><Upload size={18}/> Select or drop multiple CBD files</button><input ref={input} hidden multiple type="file" accept=".xls,.xlsx" onChange={event=>drop(event.target.files)}/><b>{files.length} {files.length===1?'file':'files'} · {count} {count===1?'style':'styles'}</b>{files.map(file=><small key={file.id}>{file.name}</small>)}</section>}
