import {useEffect,useMemo,useRef,useState} from 'react';
import {AlertTriangle,ArrowLeft,Download,FileSpreadsheet,GitCompareArrows,RotateCcw,Upload} from 'lucide-react';
import {exportComparison} from './exporter';
import {matchMaterials,matchStyles} from './matcher';
import {parseCbdFiles} from './parser';
import {clearComparison,loadComparison,saveComparison} from './persistence';
import type {ComparisonSide,ComparisonState,MaterialMatch,StyleMatch} from './types';

const empty:ComparisonState={version:1,referenceSeason:'기준 시즌',currentSeason:'비교 시즌',files:[],styles:[],styleMatches:[],materialMatches:[],step:1};
const excel=(f:File)=>/\.xlsx?$/i.test(f.name);
export default function ComparisonWorkspace({onBack}:{onBack:()=>void}){const[state,setState]=useState(empty),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[restoring,setRestoring]=useState(true);const hydrated=useRef(false);
  useEffect(()=>{loadComparison().then(saved=>{if(saved)setState(saved)}).catch(()=>setNotice('저장된 비교 작업을 복원하지 못했습니다.')).finally(()=>{hydrated.current=true;setRestoring(false)})},[]);
  useEffect(()=>{if(!hydrated.current)return;const t=setTimeout(()=>saveComparison(state).catch(()=>setNotice('비교 작업 자동 저장에 실패했습니다.')),400);return()=>clearTimeout(t)},[state]);
  const upload=async(side:ComparisonSide,files:File[])=>{const valid=files.filter(excel);if(!valid.length)return setNotice('.xls 또는 .xlsx 파일을 선택하세요.');setBusy(true);setNotice('CBD 파일을 브라우저에서 분석하고 있습니다.');const result=await parseCbdFiles(valid,side);setState(old=>{const styles=[...old.styles,...result.styles],uploaded=[...old.files,...result.files],styleMatches=styles.some(s=>s.side==='reference')&&styles.some(s=>s.side==='current')?matchStyles(styles):[];return{...old,files:uploaded,styles,styleMatches,materialMatches:[],step:styleMatches.length?2:1}});setNotice(`${side==='reference'?'기준':'비교'} 시즌에서 ${result.styles.length}개 STYLE을 인식했습니다.${result.errors.length?' '+result.errors.join(' '):''}`);setBusy(false)};
  const confirmStyles=()=>{const unresolved=state.styleMatches.filter(m=>m.status==='review'||m.status==='duplicate');if(unresolved.length)return setNotice(`검토가 필요한 STYLE 매칭이 ${unresolved.length}건 있습니다.`);setState(s=>({...s,materialMatches:s.styleMatches.filter(m=>!m.excluded).map(m=>matchMaterials(m,s.styles)),step:3,activeMatchId:s.styleMatches.find(m=>!m.excluded)?.id}));};
  const updateStyle=(id:string,patch:Partial<StyleMatch>)=>setState(s=>({...s,styleMatches:s.styleMatches.map(m=>m.id===id?{...m,...patch}:m)}));
  const active=state.styleMatches.find(m=>m.id===state.activeMatchId)||state.styleMatches.find(m=>!m.excluded),materialSet=state.materialMatches.find(m=>m.styleMatchId===active?.id);const style=(id?:string)=>state.styles.find(s=>s.id===id);const material=(side:ComparisonSide,id?:string)=>state.styles.filter(s=>s.side===side).flatMap(s=>s.materials).find(m=>m.id===id);
  const counts=useMemo(()=>({reference:state.styles.filter(s=>s.side==='reference').length,current:state.styles.filter(s=>s.side==='current').length}),[state.styles]);
  if(restoring)return <main className="comparison-loading">CBD 비교 작업을 불러오는 중입니다.</main>;
  return <div className="comparison-app"><aside><div className="brand small"><span className="brand-mark">CB</span><span className="brand-copy"><b>CBD Manager</b><small>Cost Management</small></span></div><nav className="main-nav"><button onClick={onBack}><ArrowLeft size={17}/> BOM Management</button><button className="active"><GitCompareArrows size={17}/> CBD 비교</button></nav><ol className="comparison-steps">{['CBD 파일 업로드','STYLE 매칭','자재 매칭 검토','비교 미리보기','비교 Excel 추출'].map((x,i)=><li className={state.step===i+1?'active':state.step>i+1?'done':''} key={x}>{i+1}. {x}</li>)}</ol><button className="comparison-clear" onClick={async()=>{if(confirm('CBD 비교 작업만 초기화할까요? 기존 BOM 작업은 유지됩니다.')){await clearComparison();setState(empty)}}}><RotateCcw size={15}/> CBD 비교 초기화</button></aside><main className="comparison-workspace"><header><div><span className="eyebrow">Season-to-season cost review</span><h1>CBD 비교</h1><p>두 시즌의 작성된 CBD를 자재 단위로 좌우 정렬합니다.</p></div>{state.materialMatches.length>0&&<button className="primary" onClick={()=>exportComparison(state)}><Download size={16}/> 비교 Excel 추출</button>}</header>{notice&&<div className="notice bar">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <section className="comparison-upload-grid"><UploadBox side="reference" title="기준 시즌 CBD" description="이전 시즌 또는 비교 기준이 되는 CBD 파일" season={state.referenceSeason} onSeason={referenceSeason=>setState(s=>({...s,referenceSeason}))} onFiles={upload} files={state.files.filter(f=>f.side==='reference')} count={counts.reference} busy={busy}/><UploadBox side="current" title="비교 시즌 CBD" description="최신 시즌 CBD 파일 – Group 및 정렬 기준" season={state.currentSeason} onSeason={currentSeason=>setState(s=>({...s,currentSeason}))} onFiles={upload} files={state.files.filter(f=>f.side==='current')} count={counts.current} busy={busy}/></section>
  {state.styleMatches.length>0&&<section className="comparison-panel"><h2>STYLE 매칭 검토</h2><p>자동 매칭 결과가 있더라도 반드시 확인하고 확정하세요.</p><div className="comparison-table"><table><thead><tr><th>기준 파일 / 시트 / STYLE</th><th>비교 파일 / 시트 / STYLE</th><th>방식</th><th>신뢰도</th><th>상태</th><th>수동 선택</th><th>제외</th></tr></thead><tbody>{state.styleMatches.map(m=><tr className={m.status==='review'||m.status==='duplicate'?'comparison-review':''} key={m.id}><td>{style(m.referenceId)?`${style(m.referenceId)!.fileName} · ${style(m.referenceId)!.sheetName} · ${style(m.referenceId)!.styleName}`:'—'}</td><td>{style(m.currentId)?`${style(m.currentId)!.fileName} · ${style(m.currentId)!.sheetName} · ${style(m.currentId)!.styleName}`:'—'}</td><td>{m.method}</td><td>{Math.round(m.confidence*100)}%</td><td>{m.status==='review'?<><AlertTriangle size={13}/> 검토 필요</>:m.status}</td><td><select className={m.status==='review'?'needs-review-select':''} value={m.currentId||''} onChange={e=>updateStyle(m.id,{currentId:e.target.value||undefined,status:e.target.value?'Manual':'reference-only',method:e.target.value?'Manual':'Unmatched',confidence:e.target.value?1:0})}><option value="">연결 안 함</option>{state.styles.filter(s=>s.side==='current').map(s=><option value={s.id} key={s.id}>{s.styleName}</option>)}</select></td><td><input type="checkbox" checked={!!m.excluded} onChange={e=>updateStyle(m.id,{excluded:e.target.checked})}/></td></tr>)}</tbody></table></div><button className="primary" onClick={confirmStyles}>STYLE 매칭 확정</button></section>}
  {state.materialMatches.length>0&&<section className="comparison-panel"><div className="comparison-material-head"><div><h2>자재 매칭 검토</h2><p>최종 Group은 비교 시즌을 기준으로 정렬됩니다.</p></div><select value={active?.id||''} onChange={e=>setState(s=>({...s,activeMatchId:e.target.value}))}>{state.styleMatches.filter(m=>!m.excluded).map(m=><option value={m.id} key={m.id}>{style(m.referenceId)?.styleName||'없음'} ↔ {style(m.currentId)?.styleName||'없음'}</option>)}</select></div><div className="comparison-table"><table><thead><tr><th>최종 Group</th><th>기준 시즌 Material</th><th>비교 시즌 Material</th><th>기준 Group</th><th>비교 Group</th><th>Unit</th><th>Item code</th><th>방식</th><th>신뢰도</th><th>상태</th><th>연결 변경</th></tr></thead><tbody>{materialSet?.matches.map(m=><MaterialRow key={m.id} match={m} reference={material('reference',m.referenceId)} current={material('current',m.currentId)} candidates={style(active?.referenceId)?.materials||[]} onChange={patch=>setState(s=>({...s,materialMatches:s.materialMatches.map(set=>set.styleMatchId===active?.id?{...set,matches:set.matches.map(x=>x.id===m.id?{...x,...patch}:x)}:set)}))}/>)}</tbody></table></div><div className="comparison-actions"><button onClick={()=>setState(s=>({...s,step:4}))}>비교 미리보기</button><button className="primary" onClick={()=>exportComparison(state)}><Download size={16}/> 비교 Excel 추출</button></div></section>}</main></div>}

function UploadBox({side,title,description,season,onSeason,onFiles,files,count,busy}:{side:ComparisonSide;title:string;description:string;season:string;onSeason:(v:string)=>void;onFiles:(s:ComparisonSide,f:File[])=>void;files:{id:string;name:string}[];count:number;busy:boolean}){const input=useRef<HTMLInputElement>(null),drop=(list:FileList|null)=>{if(list)onFiles(side,[...list])};return <section className="comparison-upload"><div><FileSpreadsheet/><h2>{title}</h2><p>{description}</p></div><label>시즌명<input value={season} onChange={e=>onSeason(e.target.value)}/></label><button disabled={busy} onClick={()=>{if(input.current)input.current.value='';input.current?.click()}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();drop(e.dataTransfer.files)}}><Upload size={18}/> 여러 CBD 파일 선택 또는 드롭</button><input ref={input} hidden multiple type="file" accept=".xls,.xlsx" onChange={e=>drop(e.target.files)}/><b>{files.length}개 파일 · {count}개 STYLE</b>{files.map(f=><small key={f.id}>{f.name}</small>)}</section>}
function MaterialRow({match,reference,current,candidates,onChange}:{match:MaterialMatch;reference?:any;current?:any;candidates:any[];onChange:(p:Partial<MaterialMatch>)=>void}){const review=match.status==='REVIEW';return <tr className={`material-status-${match.status.toLowerCase().replace(/ /g,'-')}`}><td>{match.finalGroup}</td><td>{reference?.material||'—'}</td><td>{current?.material||'—'}</td><td>{reference?.group||'—'}</td><td>{current?.group||'—'}</td><td>{current?.unit||reference?.unit||''}</td><td>{((current?.material||reference?.material||'').match(/JX-\d+|#[A-Z0-9-]+/i)||[])[0]||''}</td><td>{match.method}</td><td>{Math.round(match.confidence*100)}%</td><td>{review?<><AlertTriangle size={13}/> 검토 필요</>:match.status}</td><td><select className={review?'needs-review-select':''} value={match.referenceId||''} onChange={e=>onChange({referenceId:e.target.value||undefined,status:e.target.value?'MANUAL':'CURRENT ONLY',method:e.target.value?'Manual':'Unmatched',confidence:e.target.value?1:0})}><option value="">연결 해제</option>{candidates.map(x=><option key={x.id} value={x.id}>{x.material}</option>)}</select></td></tr>}
