// @vitest-environment jsdom
import 'fake-indexeddb/auto';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,render,screen,waitFor,within} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import ComparisonWorkspace from './ComparisonWorkspace';
import {clearComparison,loadComparison,saveComparison} from './persistence';
import type {CbdStyle,ComparisonState} from './types';

const exportComparisonMock=vi.hoisted(()=>vi.fn(async(_state:ComparisonState,_options:{scope:'current'|'all';stylePairIds?:string[]})=>{}));
vi.mock('./exporter',async importOriginal=>({...await importOriginal<typeof import('./exporter')>(),exportComparison:exportComparisonMock}));

const style=(id:string,side:'reference'|'current',name:string):CbdStyle=>({id,side,fileName:`${id}.xlsx`,sheetName:name,styleName:name,materials:[{id:`${side}::file::${name}::row-6::seq-1`,group:'OUTSHELL',material:`${name} MATERIAL`,size:'',unit:'YD',cost:1,usage:1,extended:1,remark:'',width:'',order:0}],summary:{totalMaterialCost:1},groupOrder:['OUTSHELL']});
const reference=style('r','reference','27 RAYCE JERSEY'),comparison=style('c','current','RAYCE JERSEY');
const state=(step:2|3):ComparisonState=>({version:2,referenceSeason:'27',currentSeason:'28',files:[],styles:[reference,comparison],styleMatches:[{id:'sm',referenceId:'r',currentId:'c',method:'Normalized',confidence:1,status:'Normalized'}],materialMatches:step===3?[{styleMatchId:'sm',clusters:[{id:'cluster',referenceRowIds:[reference.materials[0].id],currentRowId:comparison.materials[0].id,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'MATCH',confidence:1}]}]:[],step,activeMatchId:'sm'});

beforeEach(async()=>{exportComparisonMock.mockClear();await clearComparison()});afterEach(async()=>{cleanup();await clearComparison()});
describe('CBD Comparison navigation and controls',()=>{
 it('keeps both exports with Undo and Redo in the sticky toolbar and preview',async()=>{await saveComparison(state(3));const user=userEvent.setup();render(<ComparisonWorkspace onBack={()=>{}}/>);await screen.findByRole('heading',{name:'CBD Comparison'});for(const name of ['Export Current Style','Export All Styles']){const button=screen.getByRole('button',{name});expect(button.closest('.matching-toolbar')).toBeTruthy();expect((button as HTMLButtonElement).type).toBe('button')}await user.click(screen.getByRole('button',{name:/4\. Comparison Preview/}));expect(screen.getByRole('heading',{name:'Comparison Preview'})).toBeTruthy();await user.click(screen.getByRole('button',{name:/5\. Export Comparison/}));expect(screen.getByText('Review the selected comparison before generating the Excel workbook.')).toBeTruthy();expect(screen.getByRole('button',{name:'Export Current Style'})).toBeTruthy();expect(screen.getByRole('button',{name:'Export All Styles'})).toBeTruthy()});
 it('records Exclude All as one atomic history action',async()=>{await saveComparison(state(2));const user=userEvent.setup();render(<ComparisonWorkspace onBack={()=>{}}/>);const master=await screen.findByRole('checkbox',{name:/Exclude All|Clear All Exclusions/}) as HTMLInputElement,initial=master.checked;await user.click(master);expect(master.checked).toBe(!initial);await waitFor(async()=>{const saved=await loadComparison();expect(saved?.history?.past).toHaveLength(1);expect(!!saved?.history?.past[0].styleMatches[0].excluded).toBe(initial)},{timeout:2000})});
 it('exports the newly selected style pair independent of the material filter',async()=>{const multiple=structuredClone(state(3)),referenceB=style('r2','reference','27 F-16 JERSEY'),comparisonB=style('c2','current','F-16 JERSEY');multiple.styles.push(referenceB,comparisonB);multiple.styleMatches.push({id:'sm2',referenceId:'r2',currentId:'c2',method:'Manual',confidence:1,status:'Manual'});multiple.materialMatches.push({styleMatchId:'sm2',clusters:[{id:'cluster2',referenceRowIds:[referenceB.materials[0].id],currentRowId:comparisonB.materials[0].id,relationType:'one-to-one',matchSource:'manual',finalGroup:'OUTSHELL',status:'MANUAL',confidence:1}]});await saveComparison(multiple);const user=userEvent.setup();render(<ComparisonWorkspace onBack={()=>{}}/>);const pair=await screen.findByLabelText('Selected style comparison');await user.selectOptions(screen.getByLabelText('Material Filter'),'changed');await user.selectOptions(pair,'sm2');await user.click(screen.getByRole('button',{name:'Export Current Style'}));await waitFor(()=>expect(exportComparisonMock).toHaveBeenCalledTimes(1));const [exported,options]=exportComparisonMock.mock.calls[0];expect(options).toEqual({scope:'current',stylePairIds:['sm2']});expect(exported.materialMatches).toHaveLength(2);expect(exported.activeMatchId).toBe('sm2');expect(screen.getByText('Current style exported successfully.')).toBeTruthy();await user.click(screen.getByRole('button',{name:'Export All Styles'}));await waitFor(()=>expect(exportComparisonMock).toHaveBeenCalledTimes(2));expect(exportComparisonMock.mock.calls[1][1]).toEqual({scope:'all',stylePairIds:undefined});expect(screen.getByText('All styles exported successfully.')).toBeTruthy()});
 it('restores all five semantic material filters and dynamic CBD groups in one dropdown',async()=>{const filtered=state(3),refOnly={...reference.materials[0],id:'reference::file::RAYCE::row-7::seq-1',material:'REFERENCE ONLY MATERIAL',order:1},comparisonOnly={...comparison.materials[0],id:'current::file::RAYCE::row-7::seq-1',material:'COMPARISON ONLY MATERIAL',group:'SPECIAL PROCESS',order:1},reviewRef={...reference.materials[0],id:'reference::file::RAYCE::row-8::seq-1',material:'REVIEW REFERENCE',order:2},reviewCurrent={...comparison.materials[0],id:'current::file::RAYCE::row-8::seq-1',material:'REVIEW COMPARISON',order:2};filtered.styles[0].materials.push(refOnly,reviewRef);filtered.styles[1].materials.push(comparisonOnly,reviewCurrent);filtered.materialMatches[0].clusters.push({id:'ref-only',referenceRowIds:[refOnly.id],currentRowId:null,relationType:'one-to-one',matchSource:'auto',finalGroup:'TRIMS',status:'REFERENCE ONLY',confidence:0},{id:'comparison-only',referenceRowIds:[],currentRowId:comparisonOnly.id,relationType:'one-to-one',matchSource:'auto',finalGroup:'SPECIAL PROCESS',status:'CURRENT ONLY',confidence:0},{id:'review',referenceRowIds:[reviewRef.id],currentRowId:reviewCurrent.id,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'REVIEW',confidence:.5});await saveComparison(filtered);const user=userEvent.setup();render(<ComparisonWorkspace onBack={()=>{}}/>);const select=await screen.findByLabelText('Material Filter');for(const label of ['All Materials','Changed Materials Only','Reference Season Only','Comparison Season Only','Needs Review','OUTSHELL','TRIMS','SPECIAL PROCESS'])expect(within(select).getByRole('option',{name:label})).toBeTruthy();expect(screen.queryByText('Changed Items Only')).toBeNull();const count=()=>document.querySelectorAll('.material-table tbody tr').length;await user.selectOptions(select,'referenceOnly');expect(count()).toBe(1);expect(screen.getByText('Reference Only')).toBeTruthy();await user.selectOptions(select,'comparisonOnly');expect(count()).toBe(1);expect(screen.getByText('Comparison Only')).toBeTruthy();await user.selectOptions(select,'needsReview');expect(count()).toBe(1);expect(document.querySelector('.material-table tbody tr')?.textContent).toContain('Needs Review');await user.selectOptions(select,'group:SPECIAL PROCESS');expect(count()).toBe(1);await user.selectOptions(select,'changed');expect(count()).toBeGreaterThan(0)});
});
