import {describe,expect,it} from 'vitest';
import {buildComparisonWorkbook} from './exporter';
import type {CbdMaterialRow,CbdStyle,ComparisonState,MaterialMatchCluster} from './types';

const row=(id:string,side:'reference'|'current',material:string,usage:number,extended:number,order:number):CbdMaterialRow=>({id:`${side}::file::RAYCE JERSEY::row-${id}::seq-1`,group:'OUTSHELL',material,size:'',unit:'YD',cost:1,usage,extended,remark:'디지형광 $2.43',width:'',order});
const referenceRows=[row('6','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY)',.089,.1448,0),row('7','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.345,.8223,1),row('8','reference','REMOVED MATERIAL',.1,.2,2)];
const comparisonRows=[row('5','current','PRINTED SOLID FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.4751,1.5365,0),row('9','current','NEW MATERIAL',.2,.3,1)];
const style=(id:string,side:'reference'|'current',name:string,materials:CbdMaterialRow[]):CbdStyle=>({id,side,fileName:`${id}.xlsx`,sheetName:name,styleName:name,materials,summary:{totalMaterialCost:materials.reduce((total,item)=>total+(item.extended||0),0)},groupOrder:['OUTSHELL']});
const clusters:MaterialMatchCluster[]=[{id:'merged',referenceRowIds:referenceRows.slice(0,2).map(item=>item.id),currentRowId:comparisonRows[0].id,relationType:'many-to-one',matchSource:'manual',finalGroup:'OUTSHELL',status:'MERGED N:1',confidence:1},{id:'new',referenceRowIds:[],currentRowId:comparisonRows[1].id,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'CURRENT ONLY',confidence:0},{id:'removed',referenceRowIds:[referenceRows[2].id],currentRowId:null,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'REFERENCE ONLY',confidence:0}];
const state:ComparisonState={version:2,referenceSeason:'27.5',currentSeason:'28',files:[],styles:[style('r','reference','27 RAYCE JERSEY',referenceRows),style('c','current','RAYCE JERSEY',comparisonRows)],styleMatches:[{id:'sm',referenceId:'r',currentId:'c',method:'Manual',confidence:1,status:'Manual'}],materialMatches:[{styleMatchId:'sm',clusters}],step:5};

describe('comparison workbook',()=>{
 it('uses English dynamic season headers and does not duplicate seasons in the style title',()=>{const workbook=buildComparisonWorkbook(state),sheet=workbook.worksheets[1];expect(workbook.worksheets[0].getRow(1).values).toContain('Reference Season 27.5');expect(sheet.getCell('A2').value).toBe('Reference: 27 RAYCE JERSEY    |    Comparison: RAYCE JERSEY');expect(sheet.getCell('B6').value).toBe('Reference Season 27.5');expect(sheet.getCell('C6').value).toBe('Comparison Season 28')});
 it('exports an N:1 cluster once and preserves original Korean remarks',()=>{const sheet=buildComparisonWorkbook(state).worksheets[1],merged=sheet.getRows(16,3)!.find(item=>item.getCell(14).value==='MERGED N:1')!;expect(merged.getCell(8).value).toBeCloseTo(.434);expect(merged.getCell(11).value).toBeCloseTo(.9671);expect(merged.getCell(12).value).toBeCloseTo(1.5365);expect(merged.getCell(15).value).toBe('디지형광 $2.43')});
 it('uses numeric-aware difference formulas for Comparison Only and Reference Only rows',()=>{const sheet=buildComparisonWorkbook(state).worksheets[1],rows=sheet.getRows(16,3)!;for(const status of ['Comparison Only','Reference Only']){const detail=rows.find(item=>item.getCell(14).value===status)!;expect(detail.getCell(13).formula).toContain('ISNUMBER');expect(detail.getCell(13).formula).not.toContain('-"')}});
});
