import {describe,expect,it} from 'vitest';
import ExcelJS from 'exceljs';
import {buildComparisonWorkbook} from './exporter';
import type {CbdMaterialRow,CbdStyle,ComparisonState,MaterialMatchCluster} from './types';

const row=(id:string,side:'reference'|'current',material:string,usage:number,extended:number,order:number):CbdMaterialRow=>({id:`${side}::file::RAYCE JERSEY::row-${id}::seq-1`,group:'OUTSHELL',material,size:'',unit:'YD',cost:1,usage,extended,remark:'디지형광 $2.43',width:'',order});
const referenceRows=[row('6','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY)',.089,.1448,0),row('7','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.345,.8223,1),row('8','reference','REMOVED MATERIAL',.1,.2,2)];
const comparisonRows=[row('5','current','PRINTED SOLID FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.4751,1.5365,0),row('9','current','NEW MATERIAL',.2,.3,1)];
const style=(id:string,side:'reference'|'current',name:string,materials:CbdMaterialRow[]):CbdStyle=>({id,side,fileName:`${id}.xlsx`,sheetName:name,styleName:name,materials,summary:{totalMaterialCost:materials.reduce((total,item)=>total+(item.extended||0),0),finalFob:side==='reference'?6.37:7.12,fobEvidence:'explicit'},groupOrder:['OUTSHELL']});
const clusters:MaterialMatchCluster[]=[{id:'merged',referenceRowIds:referenceRows.slice(0,2).map(item=>item.id),currentRowId:comparisonRows[0].id,relationType:'many-to-one',matchSource:'manual',finalGroup:'OUTSHELL',status:'MERGED N:1',confidence:1},{id:'new',referenceRowIds:[],currentRowId:comparisonRows[1].id,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'CURRENT ONLY',confidence:0},{id:'removed',referenceRowIds:[referenceRows[2].id],currentRowId:null,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'REFERENCE ONLY',confidence:0}];
const state:ComparisonState={version:2,referenceSeason:'27.5',currentSeason:'28',files:[],styles:[style('r','reference','27 RAYCE JERSEY',referenceRows),style('c','current','RAYCE JERSEY',comparisonRows)],styleMatches:[{id:'sm',referenceId:'r',currentId:'c',method:'Manual',confidence:1,status:'Manual'}],materialMatches:[{styleMatchId:'sm',clusters}],step:5};

describe('comparison workbook',()=>{
 it('uses Korean dynamic season headers, direct STYLE MATCH FOB references, and removes only the leading season from the style title',()=>{const workbook=buildComparisonWorkbook(state),sheet=workbook.worksheets[1];expect(workbook.worksheets[0].getRow(1).values).toContain('기준 시즌 27.5');expect(sheet.getCell('A2').value).toBe('기준 시즌 27.5 – 27 RAYCE JERSEY    |    비교 시즌 28 – RAYCE JERSEY');expect(sheet.getCell('B6').value).toBe('기준 시즌 27.5');expect(sheet.getCell('C6').value).toBe('비교 시즌 28');expect(sheet.getCell('A5').value).toBe('FOB 및 그룹별 재료비 비교');expect(sheet.getCell('A7').value).toBe('FOB');expect(sheet.getCell('B7').formula).toBe("'STYLE MATCH'!I2");expect(sheet.getCell('C7').formula).toBe("'STYLE MATCH'!J2");expect(sheet.getCell('D7').formula).toBe('C7-B7');expect(sheet.getCell('E7').formula).toBe('IF(B7=0,"",D7/B7)');const standard=structuredClone(state);standard.referenceSeason='27';expect(buildComparisonWorkbook(standard).worksheets[1].getCell('A2').value).toContain('기준 시즌 27 – RAYCE JERSEY')});
 it('exports an N:1 cluster once, translates its status, and preserves original Korean remarks',()=>{const sheet=buildComparisonWorkbook(state).worksheets[1],merged=sheet.getRows(16,3)!.find(item=>item.getCell(14).value==='다대일 연결')!;expect(merged.getCell(8).value).toBeCloseTo(.434);expect(merged.getCell(11).value).toBeCloseTo(.9671);expect(merged.getCell(12).value).toBeCloseTo(1.5365);expect(merged.getCell(15).value).toBe('디지형광 $2.43')});
 it('reopens with readable detail, subtotal, summary, and total formulas',async()=>{const workbook=buildComparisonWorkbook(state);expect(workbook.calcProperties.fullCalcOnLoad).toBe(true);const buffer=await workbook.xlsx.writeBuffer(),reopened=new ExcelJS.Workbook();await reopened.xlsx.load(buffer);const sheet=reopened.worksheets[1],rows=sheet.getRows(16,3)!;for(const status of ['비교 시즌만 존재','기준 시즌만 존재']){const detail=rows.find(item=>item.getCell(14).value===status)!;expect(detail.getCell(7).formula).toBe(`F${detail.number}-E${detail.number}`);expect(detail.getCell(10).formula).toBe(`I${detail.number}-H${detail.number}`);expect(detail.getCell(13).formula).toBe(`L${detail.number}-K${detail.number}`)}expect(sheet.getCell('K19').formula).toBe('SUM(K16:K18)');expect(sheet.getCell('B8').formula).toBe('K19');expect(sheet.getCell('D8').formula).toBe('C8-B8');expect(sheet.getCell('B12').formula).toBe('SUM(B8:B11)');expect(sheet.getCell('E12').formula).toBe('IF(B12=0,"",D12/B12)');expect(sheet.autoFilter).toBeUndefined();const formulas=reopened.worksheets.flatMap(item=>{const result:string[]=[];item.eachRow(row=>row.eachCell(cell=>{if(cell.formula)result.push(cell.formula)}));return result});expect(formulas.join(' ')).not.toMatch(/ISNUMBER|SUMPRODUCT|OFFSET|INDIRECT|#VALUE!|#REF!|#DIV\/0!|#NAME\?/)});
 it('centers both header levels without reusing numeric alignment and keeps bounded widths',()=>{const sheet=buildComparisonWorkbook(state).worksheets[1];for(const cell of ['E14','H14','K14','E15','F15','G15','H15','I15','J15','K15','L15','M15'])expect(sheet.getCell(cell).alignment).toMatchObject({horizontal:'center',vertical:'middle',wrapText:false,shrinkToFit:false,indent:0});for(const cell of ['E16','F16','G16','H16','I16','J16','K16','L16','M16'])expect(sheet.getCell(cell).alignment.horizontal).toBe('right');expect(sheet.getCell('B16').alignment).toMatchObject({horizontal:'left',wrapText:true});expect(sheet.getCell('D16').alignment.horizontal).toBe('center');expect(sheet.getCell('N16').alignment.horizontal).toBe('center');expect(sheet.getCell('O16').alignment).toMatchObject({horizontal:'left',wrapText:true});expect(sheet.getCell('B6').alignment.horizontal).toBe('center');expect(sheet.getCell('B7').alignment.horizontal).toBe('right');expect(sheet.getRow(15).height).toBeGreaterThanOrEqual(22);expect(sheet.columns.map(column=>column.width)).toEqual([20,36,36,9,12,12,12,12,12,12,14,14,14,18,28])});
 it('uses an explicit original-CBD subtotal source row when details cannot reproduce it',()=>{const sourced=structuredClone(state);sourced.styles[0].groupTotals={OUTSHELL:1.4671};sourced.styles[1].groupTotals={OUTSHELL:2.1365};const sheet=buildComparisonWorkbook(sourced).worksheets[1];expect(sheet.getCell('A19').value).toBe('OUTSHELL 원본 CBD 소계');expect(sheet.getCell('O19').value).toBe('원본 CBD의 그룹 소계 사용');expect(sheet.getCell('K20').formula).toBe('K19');expect(sheet.getCell('L20').formula).toBe('L19');expect(sheet.getCell('B8').formula).toBe('K20');expect(sheet.getCell('C8').formula).toBe('L20')});
 it('uses the same workbook generator for one selected pair and all pairs',()=>{const multiple=structuredClone(state),referenceB=style('r2','reference','27 KINETIC 2',referenceRows),comparisonB=style('c2','current','KINETIC 2',comparisonRows);multiple.styles.push(referenceB,comparisonB);multiple.styleMatches.push({id:'sm2',referenceId:'r2',currentId:'c2',method:'Manual',confidence:1,status:'Manual'});multiple.materialMatches.push({styleMatchId:'sm2',clusters:structuredClone(clusters)});const current=buildComparisonWorkbook(multiple,{stylePairIds:['sm2']}),all=buildComparisonWorkbook(multiple);expect(current.worksheets).toHaveLength(2);expect(current.worksheets[0].rowCount).toBe(2);expect(current.worksheets[1].name).toBe('KINETIC 2');expect(current.worksheets[1].getCell('A2').value).toContain('KINETIC 2');expect(all.worksheets).toHaveLength(3);expect(all.worksheets[0].rowCount).toBe(3)});
});
