import ExcelJS from 'exceljs';
import {saveAs} from 'file-saver';
import type {CbdStyle,ComparisonState,MaterialMatchCluster} from './types';
const GROUPS=['OUTSHELL','TRIMS','SEWING THREAD','LABEL & PACKAGING'];
const safe=(name:string,used:Set<string>)=>{const base=(name.replace(/[\\/*?:[\]]/g,' ').trim()||'Comparison').slice(0,31);let value=base,n=2;while(used.has(value))value=`${base.slice(0,27)} ${n++}`;used.add(value);return value};
const num=(v?:number)=>v===undefined?'':v;
const style=(state:ComparisonState,id?:string)=>state.styles.find(s=>s.id===id);
const material=(s:CbdStyle|undefined,id?:string)=>s?.materials.find(m=>m.id===id);
const mappedAmount=(s:CbdStyle|undefined,clusters:MaterialMatchCluster[],group:string,side:'reference'|'current')=>{const ids=new Set<string>();clusters.filter(c=>c.finalGroup.toUpperCase()===group).forEach(c=>side==='reference'?c.referenceRowIds.forEach(id=>ids.add(id)):c.currentRowId&&ids.add(c.currentRowId));const values=[...ids].map(id=>material(s,id)?.extended).filter((v):v is number=>v!==undefined);return values.length?values.reduce((a,b)=>a+b,0):undefined};
const fill=(argb:string):ExcelJS.Fill=>({type:'pattern',pattern:'solid',fgColor:{argb}});
export async function exportComparison(state:ComparisonState){const wb=new ExcelJS.Workbook(),summary=wb.addWorksheet('STYLE MATCH'),used=new Set<string>(['STYLE MATCH']);summary.views=[{state:'frozen',ySplit:1}];summary.addRow(['기준 시즌','기준 STYLE','비교 시즌','비교 STYLE','매칭 방식','상태','기준 Total Material Cost','비교 Total Material Cost','기준 FOB','비교 FOB']);summary.getRow(1).font={bold:true,color:{argb:'FFFFFF'}};summary.getRow(1).fill=fill('1E3A8A');
 // @ts-ignore ExcelJS runtime property is missing in its type declaration.
 for(const sm of state.styleMatches.filter(m=>!m.excluded)){const r=style(state,sm.referenceId),c=style(state,sm.currentId),clusters=state.materialMatches.find(x=>x.styleMatchId===sm.id)?.clusters||[];summary.addRow([state.referenceSeason,r?.styleName||'—',state.currentSeason,c?.styleName||'—',sm.method,sm.status,r?.summary.totalMaterialCost??'',c?.summary.totalMaterialCost??'',r?.summary.fob??'',c?.summary.fob??'']);const ws=wb.addWorksheet(safe(c?.styleName||r?.styleName||'Unmatched',used));ws.showGridLines=false;ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};ws.views=[{state:'frozen',ySplit:12}];ws.mergeCells('A1:P1');ws.getCell('A1').value='FLY Racing CBD Comparison Sheet';ws.getCell('A1').font={bold:true,size:16,color:{argb:'FFFFFF'}};ws.getCell('A1').fill=fill('1E3A8A');ws.getCell('A1').alignment={horizontal:'center'};ws.mergeCells('A2:P2');ws.getCell('A2').value=`기준 시즌 ${state.referenceSeason} – ${r?.styleName||'없음'}    |    비교 시즌 ${state.currentSeason} – ${c?.styleName||'없음'}    |    비교 방향: ${state.currentSeason} – ${state.referenceSeason}`;ws.getCell('A2').font={bold:true};ws.getCell('A2').fill=fill('DBEAFE');ws.mergeCells('A3:P3');ws.getCell('A3').value=`생성일: ${new Date().toLocaleDateString()}`;
   ws.getCell('A5').value='그룹별 재료비 비교';ws.getCell('A5').font={bold:true,size:13};ws.getRow(6).values=['CBD Group','기준 시즌','비교 시즌','차액','변동률'];ws.getRow(6).font={bold:true,color:{argb:'FFFFFF'}};ws.getRow(6).fill=fill('1E3A8A');let gr=7;for(const g of [...GROUPS,'TOTAL MATERIAL COST']){const a=g==='TOTAL MATERIAL COST'?r?.summary.totalMaterialCost:mappedAmount(r,clusters,g,'reference'),b=g==='TOTAL MATERIAL COST'?c?.summary.totalMaterialCost:mappedAmount(c,clusters,g,'current');ws.getCell(gr,1).value=g;ws.getCell(gr,2).value=num(a);ws.getCell(gr,3).value=num(b);ws.getCell(gr,4).value={formula:`IF(OR(B${gr}=\"\",C${gr}=\"\"),\"\",C${gr}-B${gr})`};ws.getCell(gr,5).value={formula:`IF(OR(B${gr}=\"\",B${gr}=0,D${gr}=\"\"),\"\",D${gr}/B${gr})`};ws.getCell(gr,2).numFmt=ws.getCell(gr,3).numFmt=ws.getCell(gr,4).numFmt='$0.0000';ws.getCell(gr,5).numFmt='0.0%';if(g==='TOTAL MATERIAL COST')ws.getRow(gr).fill=fill('DBEAFE');gr++}
   ws.getCell('A13').value='자재 상세 비교';ws.getCell('A13').font={bold:true,size:13};ws.mergeCells('B14:C14');ws.getCell('B14').value='Material';ws.mergeCells('E14:G14');ws.getCell('E14').value='Cost per Unit';ws.mergeCells('H14:J14');ws.getCell('H14').value='Usage';ws.mergeCells('K14:M14');ws.getCell('K14').value='Extended Cost';ws.getCell('A14').value='Group';ws.getCell('D14').value='Unit';ws.getCell('N14').value='상태';ws.getCell('O14').value='Remark';ws.getRow(14).font={bold:true,color:{argb:'FFFFFF'}};ws.getRow(14).fill=fill('1E3A8A');ws.getRow(15).values=['','기준','비교','Unit','기준','비교','차이','기준','비교','차이','기준','비교','차이','상태','Remark'];ws.getRow(15).font={bold:true};ws.getRow(15).fill=fill('BFDBFE');const ordered=[...clusters].sort((a,b)=>(material(c,a.currentRowId||undefined)?.order??99999)-(material(c,b.currentRowId||undefined)?.order??99999));let row=16;for(const cluster of ordered){const refs=cluster.referenceRowIds.map(id=>material(r,id)).filter(Boolean),cm=material(c,cluster.currentRowId||undefined),total=(key:'cost'|'usage'|'extended')=>{const values=refs.map(x=>x?.[key]).filter((x):x is number=>x!==undefined);return values.length?values.reduce((a,b)=>a+b,0):undefined};ws.getCell(row,1).value=cluster.finalGroup;ws.getCell(row,2).value=refs.map(x=>x?.material).join('\n');ws.getCell(row,3).value=cm?.material||'';ws.getCell(row,4).value=cm?.unit||refs[0]?.unit||'';ws.getCell(row,5).value=num(total('cost'));ws.getCell(row,6).value=num(cm?.cost);ws.getCell(row,7).value={formula:`IF(OR(E${row}=\"\",F${row}=\"\"),\"\",F${row}-E${row})`};ws.getCell(row,8).value=num(total('usage'));ws.getCell(row,9).value=num(cm?.usage);ws.getCell(row,10).value={formula:`IF(OR(H${row}=\"\",I${row}=\"\"),\"\",I${row}-H${row})`};ws.getCell(row,11).value=num(total('extended'));ws.getCell(row,12).value=num(cm?.extended);ws.getCell(row,13).value={formula:`IF(AND(K${row}=\"\",L${row}=\"\"),\"\",L${row}-K${row})`};ws.getCell(row,14).value=cluster.status==='CURRENT ONLY'?'NEW':cluster.status==='REFERENCE ONLY'?'REMOVED':cluster.status;ws.getCell(row,15).value=cm?.remark||refs.map(x=>x?.remark).filter(Boolean).join('\n');for(const col of [5,6,7,11,12,13])ws.getCell(row,col).numFmt='$0.0000';for(const col of [8,9,10])ws.getCell(row,col).numFmt='0.0000';if(cluster.status==='REVIEW')ws.getRow(row).font={bold:true,color:{argb:'DC2626'}};else if(cluster.status==='CURRENT ONLY')ws.getRow(row).fill=fill('DCFCE7');else if(cluster.status==='REFERENCE ONLY')ws.getRow(row).fill=fill('F3F4F6');else if(cluster.status==='GROUP CHANGED')ws.getRow(row).fill=fill('FFEDD5');else if(cluster.status==='NAME CHANGED')ws.getRow(row).fill=fill('FEF3C7');else if(cluster.status==='MERGED N:1')ws.getRow(row).fill=fill('EDE9FE');row++}
   const widths=[18,38,38,10,14,14,14,12,12,12,15,15,15,18,42];widths.forEach((w,i)=>ws.getColumn(i+1).width=w);ws.eachRow(x=>x.alignment={vertical:'top',wrapText:true});ws.getRow(1).height=26;ws.getRow(2).height=24;for(let i=16;i<row;i++)ws.getRow(i).height=32;
 }
 const buffer=await wb.xlsx.writeBuffer();saveAs(new Blob([buffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`CBD_Comparison_${state.referenceSeason||'Reference'}_vs_${state.currentSeason||'Current'}.xlsx`);
}
