import {describe,expect,it} from 'vitest';
import ExcelJS from 'exceljs';
import {buildComparisonWorkbook} from './exporter';
import type {CbdMaterialRow,CbdStyle,ComparisonState,MaterialMatchCluster} from './types';

const row=(id:string,side:'reference'|'current',material:string,usage:number,extended:number,order:number):CbdMaterialRow=>({id:`${side}::file::RAYCE JERSEY::row-${id}::seq-1`,group:'OUTSHELL',material,size:'',unit:'YD',cost:1,usage,extended,remark:'디지형광 $2.43',width:'',order});
const referenceRows=[row('6','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY)',.089,.1448,0),row('7','reference','PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.345,.8223,1),row('8','reference','REMOVED MATERIAL',.1,.2,2)];
const comparisonRows=[row('5','current','PRINTED SOLID FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',.4751,1.5365,0),row('9','current','NEW MATERIAL',.2,.3,1)];
const style=(id:string,side:'reference'|'current',name:string,materials:CbdMaterialRow[]):CbdStyle=>({id,side,fileName:`${id}.xlsx`,sheetName:name,styleName:name,materials,summary:{totalMaterialCost:materials.reduce((total,item)=>total+(item.extended||0),0)},groupOrder:['OUTSHELL']});
const clusters:MaterialMatchCluster[]=[{id:'merged',referenceRowIds:referenceRows.slice(0,2).map(item=>item.id),currentRowId:comparisonRows[0].id,relationType:'many-to-one',matchSource:'manual',finalGroup:'OUTSHELL',status:'MERGED N:1',confidence:1},{id:'new',referenceRowIds:[],currentRowId:comparisonRows[1].id,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'CURRENT ONLY',confidence:0},{id:'removed',referenceRowIds:[referenceRows[2].id],currentRowId:null,relationType:'one-to-one',matchSource:'auto',finalGroup:'OUTSHELL',status:'REFERENCE ONLY',confidence:0}];
const state:ComparisonState={version:2,referenceSeason:'27.5',currentSeason:'28',files:[],styles:[style('r','reference','27 RAYCE JERSEY',referenceRows),style('c','current','RAYCE JERSEY',comparisonRows)],styleMatches:[{id:'sm',referenceId:'r',currentId:'c',method:'Manual',confidence:1,status:'Manual'}],materialMatches:[{styleMatchId:'sm',clusters}],step:5};

describe('comparison workbook',()=>{
 it('uses Korean dynamic season headers and removes only the leading season from the style title',()=>{const workbook=buildComparisonWorkbook(state),sheet=workbook.worksheets[1];expect(workbook.worksheets[0].getRow(1).values).toContain('기준 시즌 27.5');expect(sheet.getCell('A2').value).toBe('기준 시즌 27.5 – 27 RAYCE JERSEY    |    비교 시즌 28 – RAYCE JERSEY');expect(sheet.getCell('B6').value).toBe('기준 시즌 27.5');expect(sheet.getCell('C6').value).toBe('비교 시즌 28');expect(sheet.getCell('A5').value).toBe('그룹별 재료비 비교');const standard=structuredClone(state);standard.referenceSeason='27';expect(buildComparisonWorkbook(standard).worksheets[1].getCell('A2').value).toContain('기준 시즌 27 – RAYCE JERSEY')});
 it('exports an N:1 cluster once, translates its status, and preserves original Korean remarks',()=>{const sheet=buildComparisonWorkbook(state).worksheets[1],merged=sheet.getRows(16,3)!.find(item=>item.getCell(14).value==='다대일 연결')!;expect(merged.getCell(8).value).toBeCloseTo(.434);expect(merged.getCell(11).value).toBeCloseTo(.9671);expect(merged.getCell(12).value).toBeCloseTo(1.5365);expect(merged.getCell(15).value).toBe('디지형광 $2.43')});
 it('reopens the generated file with numeric-aware formulas and no spreadsheet error literals',async()=>{const workbook=buildComparisonWorkbook(state),buffer=await workbook.xlsx.writeBuffer(),reopened=new ExcelJS.Workbook();await reopened.xlsx.load(buffer);const sheet=reopened.worksheets[1],rows=sheet.getRows(16,3)!;for(const status of ['비교 시즌만 존재','기준 시즌만 존재']){const detail=rows.find(item=>item.getCell(14).value===status)!;expect(detail.getCell(13).formula).toContain('ISNUMBER');expect(detail.getCell(7).formula).toContain('AND(ISNUMBER');expect(detail.getCell(10).formula).toContain('AND(ISNUMBER')}const formulas=reopened.worksheets.flatMap(item=>{const result:string[]=[];item.eachRow(row=>row.eachCell(cell=>{if(cell.formula)result.push(cell.formula)}));return result});expect(formulas.join(' ')).not.toMatch(/#VALUE!|#REF!|#DIV\/0!|#NAME\?/)});
});
