import {describe,expect,it} from 'vitest';
import {matchMaterials,matchStyles} from './matcher';
import {normalizeMaterial,normalizeStyle} from './normalize';
import type {CbdStyle} from './types';
const style=(id:string,side:'reference'|'current',name:string,items:{material:string;group:string;remark?:string}[]=[]):CbdStyle=>({id,side,fileName:`${id}.xlsx`,sheetName:name,styleName:name,summary:{},groupOrder:[],materials:items.map((x,i)=>({id:`${id}-${i}`,...x,size:'',unit:'YD',cost:1,usage:1,loss:.05,extended:1.05,remark:x.remark||'',width:'58',order:i}))});
describe('CBD comparison matching',()=>{
 it('normalizes seasons without deleting material codes',()=>{expect(normalizeStyle('27 RAYCE JERSEY CBD SHEET')).toBe('RAYCE JERSEY');expect(normalizeMaterial('FLY RACING 26 JERSEY+JX-306',true)).toContain('JX-306')});
 it('matches normal and big-size aliases but not different KINETIC identifiers',()=>{const result=matchStyles([style('r1','reference','27 RAYCE JERSEY'),style('r2','reference','27 F-16 JERSEY (3XL ~ 5XL)'),style('r3','reference','27 KINETIC YOUTH 3 JERSEY'),style('c1','current','RAYCE JERSEY'),style('c2','current','F-16 JERSEY (BIG SIZES)'),style('c3','current','KINETIC YOUTH 1 JERSEY')]);expect(result.find(x=>x.referenceId==='r1')?.currentId).toBe('c1');expect(result.find(x=>x.referenceId==='r2')?.currentId).toBe('c2');expect(result.find(x=>x.referenceId==='r3')?.currentId).toBeUndefined()});
 it('keeps non-polygiene JX-306 separate and uses current group',()=>{const r=style('r','reference','RAYCE',[{material:'PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',group:'TRIMS'},{material:'PRINTED FLY RACING 26 RAYCE JERSEY+JX-306 (POLY)',group:'TRIMS'}]),c=style('c','current','RAYCE',[{material:'PRINTED SOLID FLY RACING 26 RAYCE JERSEY+JX-306 (POLY) POLYGIENE',group:'OUTSHELL'}]);const sm={id:'m',referenceId:'r',currentId:'c',method:'Normalized',confidence:1,status:'Normalized' as const},set=matchMaterials(sm,[r,c]);expect(set.clusters.find(x=>x.currentRowId==='c-0')).toMatchObject({referenceRowIds:['r-0'],finalGroup:'OUTSHELL',status:'GROUP CHANGED'});expect(set.clusters.find(x=>x.referenceRowIds.includes('r-1'))).toMatchObject({status:'REFERENCE ONLY'})});
 it('matches JX-12 when the current name adds an FR suffix',()=>{const r=style('r','reference','RAYCE',[{material:'PRINTED FLY RACING 26 RAYCE JERSEY+JX-12 (POLY)',group:'OUTSHELL'}]),c=style('c','current','RAYCE',[{material:'PRINTED FLY RACING 26 RAYCE JERSEY+JX-12 (POLY) - FR',group:'OUTSHELL'}]);const set=matchMaterials({id:'m',referenceId:'r',currentId:'c',method:'Normalized',confidence:1,status:'Normalized'},[r,c]);expect(set.clusters[0]).toMatchObject({referenceRowIds:['r-0'],currentRowId:'c-0',status:'NAME CHANGED'})});
 it('marks duplicate styles as conflicts',()=>{const result=matchStyles([style('r1','reference','RAYCE'),style('r2','reference','RAYCE'),style('c','current','RAYCE')]);expect(result.some(x=>x.status==='duplicate')).toBe(true)});
});
