import {extractMaterialAttributes,normalizeMaterialName,normalizeStyle,styleKey} from './normalize';
import type {CbdMaterialRow,CbdStyle,MaterialMatchCluster,MaterialMatchEvidence,MaterialMatchSet,StyleMatch} from './types';
export const MATERIAL_MATCHER_VERSION=3;
const AUTO_THRESHOLD=90,MIN_MARGIN=8;
const id=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const styleAlias=(a:string,b:string)=>{const x=styleKey(a),y=styleKey(b);if(x===y)return true;return /F-16 JERSEY \(3XL\s*~\s*5XL\)/.test(normalizeStyle(a))&&/F-16 JERSEY \(BIG SIZES\)/.test(normalizeStyle(b))||/F-16 JERSEY \(3XL\s*~\s*5XL\)/.test(normalizeStyle(b))&&/F-16 JERSEY \(BIG SIZES\)/.test(normalizeStyle(a))};
export function matchStyles(styles:CbdStyle[]):StyleMatch[]{const refs=styles.filter(s=>s.side==='reference'),curr=styles.filter(s=>s.side==='current'),used=new Set<string>(),out:StyleMatch[]=[],refCounts=new Map<string,number>(),curCounts=new Map<string,number>();refs.forEach(s=>refCounts.set(styleKey(s.styleName),(refCounts.get(styleKey(s.styleName))||0)+1));curr.forEach(s=>curCounts.set(styleKey(s.styleName),(curCounts.get(styleKey(s.styleName))||0)+1));for(const r of refs){const exact=curr.filter(c=>styleKey(c.styleName)===styleKey(r.styleName)&&!used.has(c.id)),alias=curr.filter(c=>styleAlias(r.styleName,c.styleName)&&!used.has(c.id)),candidate=exact[0]||alias[0],duplicate=(refCounts.get(styleKey(r.styleName))||0)>1||(candidate&&(curCounts.get(styleKey(candidate.styleName))||0)>1);if(candidate){used.add(candidate.id);const method=exact.length?'Normalized':'Alias';out.push({id:id(),referenceId:r.id,currentId:candidate.id,method,confidence:exact.length?1:.9,status:duplicate?'duplicate':(exact.length>1||alias.length>1)?'review':method as StyleMatch['status']})}else out.push({id:id(),referenceId:r.id,method:'Unmatched',confidence:0,status:duplicate?'duplicate':'reference-only'})}for(const c of curr)if(!used.has(c.id))out.push({id:id(),currentId:c.id,method:'Unmatched',confidence:0,status:(curCounts.get(styleKey(c.styleName))||0)>1?'duplicate':'current-only'});return out}
const sameSet=(a:string[],b:string[])=>a.length===b.length&&a.every(value=>b.includes(value)),intersects=(a:string[],b:string[])=>a.some(value=>b.includes(value)),conflicting=(a:string[],b:string[])=>a.length>0&&b.length>0&&!intersects(a,b);
const unit=(value:string)=>value.trim().toUpperCase().replace(/\s+/g,''),compatibleUnit=(a:string,b:string)=>!unit(a)||!unit(b)||unit(a)===unit(b);
const jaccard=(a:string[],b:string[])=>{const left=new Set(a),right=new Set(b),common=[...left].filter(token=>right.has(token)).length;return common/Math.max(1,new Set([...left,...right]).size)};
const generic=(tokens:string[])=>tokens.length<=2&&tokens.some(token=>['PRINT','MATERIAL','LABEL','WEBBING','BUCKLE','FABRIC','TAPE'].includes(token));
export interface MaterialCandidateScore {score:number;method:MaterialMatchEvidence['method'];blocked?:string;evidence:MaterialMatchEvidence}
export function scoreMaterialCandidate(reference:CbdMaterialRow,current:CbdMaterialRow):MaterialCandidateScore {
 const a=extractMaterialAttributes(reference.material),b=extractMaterialAttributes(current.material),matchedCodes=a.codes.filter(code=>b.codes.includes(code)),matchedTokens=a.coreTokens.filter(token=>b.coreTokens.includes(token));
 const remarkA=extractMaterialAttributes(reference.remark),remarkB=extractMaterialAttributes(current.remark);
 const base={score:0,method:'Needs Review' as const,matchedCodes,matchedTokens,ignoredReference:a.auxiliaryTokens,ignoredComparison:b.auxiliaryTokens,groupAssessment:reference.group===current.group?'Same group':'Group changed',unitAssessment:compatibleUnit(reference.unit,current.unit)?'Compatible':'Conflict',reason:''};
 const block=(reason:string):MaterialCandidateScore=>({score:0,method:'Needs Review',blocked:reason,evidence:{...base,reason}});
 if(!compatibleUnit(reference.unit,current.unit))return block(`UNIT conflict: ${reference.unit} vs ${current.unit}`);if(conflicting(a.codes,b.codes))return block('Both rows have different material codes.');if(conflicting(a.styles,b.styles))return block(`Style identifier conflict: ${a.styles.join(', ')} vs ${b.styles.join(', ')}`);if(conflicting(a.demographics,b.demographics))return block('Gender or age qualifier conflict.');if(conflicting(a.composition,b.composition))return block('Construction attribute conflict.');if(conflicting(a.positions,b.positions)||conflicting(remarkA.positions,remarkB.positions))return block('Position or Source Structure qualifier conflict.');if(conflicting(a.productTypes,b.productTypes))return block(`Product type conflict: ${a.productTypes.join(', ')} vs ${b.productTypes.join(', ')}`);
 const sharedSpecs=a.specs.filter(spec=>b.specs.includes(spec));if(a.specs.length&&b.specs.length&&!sharedSpecs.length)return block(`Specification conflict: ${a.specs.join(', ')} vs ${b.specs.join(', ')}`);
 const sameGroup=reference.group===current.group,groupPenalty=sameGroup?0:5,hasIdentity=a.codes.length+a.specs.length+a.styles.length+a.composition.length>0;if(generic(a.coreTokens)&&!hasIdentity){if(!reference.remark||normalizeMaterialName(reference.remark)!==normalizeMaterialName(current.remark))return block('The shared name is too generic without matching Remark or Source Structure evidence.');}
 let score=0,method:MaterialMatchEvidence['method']='Needs Review',reason='Insufficient distinctive material identity.';
 if(normalizeMaterialName(reference.material)===normalizeMaterialName(current.material)){score=100;method='Exact';reason='Normalized full material name is identical.'}else if(matchedCodes.length){score=99;method='Code Match';reason=`Material code matched: ${matchedCodes.join(', ')}.`}else if(sameSet(a.coreTokens,b.coreTokens)&&a.coreTokens.length>=2){score=96;method='Token Match';reason='Distinctive core tokens and attributes match; word order or auxiliary text differs.'}else{const containment=a.coreTokens.every(token=>b.coreTokens.includes(token))||b.coreTokens.every(token=>a.coreTokens.includes(token)),similarity=jaccard(a.coreTokens,b.coreTokens);if(containment&&!generic(a.coreTokens.length<=b.coreTokens.length?a.coreTokens:b.coreTokens)){score=92;method='Normalized';reason='One core name uniquely contains the other with compatible attributes.'}else if(similarity>=.8&&!generic(matchedTokens)){score=Math.round(82+similarity*10);method='Similar';reason=`Core token similarity is ${Math.round(similarity*100)}%.`}}
 score-=groupPenalty;if(!sameGroup&&score<94)return block('Different GROUP without sufficiently strong material identity.');const evidence:MaterialMatchEvidence={...base,score,method,reason,matchedTokens};return{score,method,evidence};
}
type Pair={reference:CbdMaterialRow;current:CbdMaterialRow;candidate:MaterialCandidateScore};
// Hungarian maximum-weight 1:1 assignment. Stable IDs make ties independent of workbook row order.
const maximumAssignment=(refs:CbdMaterialRow[],currents:CbdMaterialRow[],candidates:Map<string,MaterialCandidateScore>):Pair[]=>{
 const rs=[...refs].sort((a,b)=>a.id.localeCompare(b.id)),cs=[...currents].sort((a,b)=>a.id.localeCompare(b.id)),size=Math.max(rs.length,cs.length);if(!size)return[];
 const cost=Array.from({length:size},(_,i)=>Array.from({length:size},(_,j)=>100-(i<rs.length&&j<cs.length?(candidates.get(`${rs[i].id}\0${cs[j].id}`)?.score||0):0)));
 const u=Array(size+1).fill(0),v=Array(size+1).fill(0),p=Array(size+1).fill(0),way=Array(size+1).fill(0);
 for(let i=1;i<=size;i++){p[0]=i;let j0=0;const minv=Array(size+1).fill(Infinity),used=Array(size+1).fill(false);do{used[j0]=true;const i0=p[j0];let delta=Infinity,j1=0;for(let j=1;j<=size;j++)if(!used[j]){const cur=cost[i0-1][j-1]-u[i0]-v[j];if(cur<minv[j]){minv[j]=cur;way[j]=j0}if(minv[j]<delta){delta=minv[j];j1=j}}for(let j=0;j<=size;j++)if(used[j]){u[p[j]]+=delta;v[j]-=delta}else minv[j]-=delta;j0=j1}while(p[j0]!==0);do{const j1=way[j0];p[j0]=p[j1];j0=j1}while(j0)}
 const pairs:Pair[]=[];for(let j=1;j<=size;j++){const ri=p[j]-1,ci=j-1;if(ri<0||ri>=rs.length||ci>=cs.length)continue;const candidate=candidates.get(`${rs[ri].id}\0${cs[ci].id}`);if(candidate)pairs.push({reference:rs[ri],current:cs[ci],candidate})}return pairs;
};
const close=(a:number|undefined,b:number|undefined)=>a!==undefined&&b!==undefined&&Math.abs(a-b)<=Math.max(.0001,Math.abs(b)*.01);
export function evaluateManyToOneMatches(clusters:MaterialMatchCluster[],reference:CbdMaterialRow[],current:CbdMaterialRow[]):MaterialMatchCluster[]{
 const refById=new Map(reference.map(row=>[row.id,row])),curById=new Map(current.map(row=>[row.id,row]));
 // Resolve a fully ambiguous duplicate set only when the aggregate quantities independently prove the merge.
 for(const targetCluster of [...clusters].filter(cluster=>cluster.currentRowId&&!cluster.referenceRowIds.length)){
  const target=curById.get(targetCluster.currentRowId!);if(!target||generic(extractMaterialAttributes(target.material).coreTokens))continue;
  const candidates=clusters.filter(cluster=>cluster.status==='REFERENCE ONLY'&&cluster.referenceRowIds.length===1).map(cluster=>({cluster,row:refById.get(cluster.referenceRowIds[0])})).filter(item=>item.row&&scoreMaterialCandidate(item.row,target).score>=96) as {cluster:MaterialMatchCluster;row:CbdMaterialRow}[];
  if(candidates.length<2)continue;const usage=candidates.reduce((sum,item)=>sum+(item.row.usage??0),0),extended=candidates.reduce((sum,item)=>sum+(item.row.extended??0),0);if(!close(usage,target.usage)&&!close(extended,target.extended))continue;
  targetCluster.referenceRowIds=candidates.map(item=>item.row.id).sort();targetCluster.relationType='many-to-one';targetCluster.status='MERGED N:1';targetCluster.confidence=.96;targetCluster.evidence={...scoreMaterialCandidate(candidates[0].row,target).evidence,method:'Merged N:1',reason:'Equivalent reference rows reconcile to one comparison row by Usage or Extended Cost.'};const removed=new Set(candidates.map(item=>item.cluster.id));clusters=clusters.filter(cluster=>!removed.has(cluster.id));
 }
 for(const orphan of [...clusters].filter(cluster=>cluster.status==='REFERENCE ONLY'&&cluster.referenceRowIds.length===1)){const row=refById.get(orphan.referenceRowIds[0]);if(!row)continue;const candidates=clusters.filter(cluster=>cluster.currentRowId&&cluster.referenceRowIds.length&&cluster.matchSource==='auto').map(cluster=>{const target=curById.get(cluster.currentRowId!),refs=cluster.referenceRowIds.map(id=>refById.get(id)).filter(Boolean) as CbdMaterialRow[];if(!target||generic(extractMaterialAttributes(target.material).coreTokens))return undefined;const scored=scoreMaterialCandidate(row,target),all=[...refs,row],usage=all.reduce((sum,item)=>sum+(item.usage??0),0),extended=all.reduce((sum,item)=>sum+(item.extended??0),0),quantitative=close(usage,target.usage)||close(extended,target.extended),sameIdentity=refs.every(item=>scoreMaterialCandidate(item,row).score>=96);return scored.score>=96&&sameIdentity&&quantitative?{cluster,scored}:undefined}).filter(Boolean) as {cluster:MaterialMatchCluster;scored:MaterialCandidateScore}[];if(candidates.length!==1)continue;const target=candidates[0].cluster;target.referenceRowIds.push(row.id);target.referenceRowIds.sort();target.relationType='many-to-one';target.status='MERGED N:1';target.evidence={...candidates[0].scored.evidence,method:'Merged N:1',reason:'Equivalent reference rows reconcile to one comparison row by Usage or Extended Cost.'};clusters=clusters.filter(cluster=>cluster.id!==orphan.id)}return clusters}
export function assignMaterialMatches(reference:CbdMaterialRow[],current:CbdMaterialRow[],locked:MaterialMatchCluster[]=[]):MaterialMatchCluster[]{
 const lockedRefs=new Set(locked.flatMap(c=>c.referenceRowIds)),lockedCurrents=new Set(locked.map(c=>c.currentRowId).filter(Boolean) as string[]),refs=reference.filter(r=>!lockedRefs.has(r.id)),currents=current.filter(c=>!lockedCurrents.has(c.id));
 const all=refs.flatMap(r=>currents.map(c=>({r,c,candidate:scoreMaterialCandidate(r,c)}))),eligible=new Map(all.filter(x=>x.candidate.score>=AUTO_THRESHOLD).map(x=>[`${x.r.id}\0${x.c.id}`,x.candidate]));
 const margin=new Map<string,number>();for(const r of refs){const scores=all.filter(x=>x.r.id===r.id&&x.candidate.score>=AUTO_THRESHOLD).map(x=>x.candidate.score).sort((a,b)=>b-a);margin.set(r.id,(scores[0]??0)-(scores[1]??0))}
 const ambiguousRefs=new Set(refs.filter(r=>[...eligible.keys()].filter(key=>key.startsWith(`${r.id}\0`)).length>1&&(margin.get(r.id)??0)<MIN_MARGIN).map(r=>r.id));
 const ambiguousCurrents=new Set(currents.filter(c=>{const scores=all.filter(x=>x.c.id===c.id&&x.candidate.score>=AUTO_THRESHOLD).map(x=>x.candidate.score).sort((a,b)=>b-a);return scores.length>1&&scores[0]-scores[1]<MIN_MARGIN}).map(c=>c.id));
 const pairs=maximumAssignment(refs,currents,eligible).filter(pair=>!ambiguousRefs.has(pair.reference.id)&&!ambiguousCurrents.has(pair.current.id)),matchedR=new Set(pairs.map(x=>x.reference.id)),matchedC=new Set(pairs.map(x=>x.current.id));
 const matched:MaterialMatchCluster[]=pairs.map(({reference:r,current:c,candidate})=>({id:id(),referenceRowIds:[r.id],currentRowId:c.id,relationType:'one-to-one',matchSource:'auto',manualLocked:false,finalGroup:c.group,status:r.group!==c.group?'GROUP CHANGED':candidate.method.toUpperCase() as MaterialMatchCluster['status'],confidence:candidate.score/100,evidence:candidate.evidence}));
 const referenceOnly:MaterialMatchCluster[]=refs.filter(r=>!matchedR.has(r.id)).map(r=>({id:id(),referenceRowIds:[r.id],currentRowId:null,relationType:'one-to-one',matchSource:'auto',finalGroup:r.group,status:'REFERENCE ONLY',confidence:0}));
 const comparisonOnly:MaterialMatchCluster[]=currents.filter(c=>!matchedC.has(c.id)).map(c=>{const choices=all.filter(x=>x.c.id===c.id).sort((a,b)=>b.candidate.score-a.candidate.score),ambiguous=choices[0]?.candidate.score>=AUTO_THRESHOLD&&((choices[0].candidate.score-(choices[1]?.candidate.score??0)<MIN_MARGIN)||ambiguousRefs.has(choices[0].r.id));return{id:id(),referenceRowIds:[],currentRowId:c.id,relationType:'one-to-one',matchSource:'auto',finalGroup:c.group,status:ambiguous?'REVIEW':'CURRENT ONLY',confidence:(choices[0]?.candidate.score??0)/100,evidence:choices[0]?.candidate.evidence}});
 return evaluateManyToOneMatches([...locked.map(c=>structuredClone(c)),...matched,...referenceOnly,...comparisonOnly],reference,current);
}
export function matchMaterials(styleMatch:StyleMatch,styles:CbdStyle[],existing?:MaterialMatchSet):MaterialMatchSet{const reference=styles.find(s=>s.id===styleMatch.referenceId),current=styles.find(s=>s.id===styleMatch.currentId),referenceIds=new Set(reference?.materials.map(row=>row.id)||[]),currentIds=new Set(current?.materials.map(row=>row.id)||[]),locked=(existing?.clusters||[]).filter(c=>(c.manualLocked||c.matchSource==='manual')&&c.referenceRowIds.every(rowId=>referenceIds.has(rowId))&&(!c.currentRowId||currentIds.has(c.currentRowId))),clusters=assignMaterialMatches(reference?.materials||[],current?.materials||[],locked),integrity=validateMaterialMatchIntegrity(reference?.materials||[],current?.materials||[],clusters);if(!integrity.valid)throw new Error(`Material matching integrity failed: ${integrity.errors.join(' ')}`);return{styleMatchId:styleMatch.id,clusters,matcherVersion:MATERIAL_MATCHER_VERSION}}

export interface MatchIntegrity {valid:boolean;errors:string[];referenceTotal:number;comparisonTotal:number;coveredReferenceTotal:number;coveredComparisonTotal:number}
export function validateMaterialMatchIntegrity(reference:CbdMaterialRow[],current:CbdMaterialRow[],clusters:MaterialMatchCluster[],tolerance=.0001):MatchIntegrity {
 const errors:string[]=[],referenceIds=clusters.flatMap(c=>c.referenceRowIds),comparisonIds=clusters.map(c=>c.currentRowId).filter(Boolean) as string[],count=(ids:string[],id:string)=>ids.filter(value=>value===id).length;
 for(const row of reference)if(count(referenceIds,row.id)!==1)errors.push(`Reference row ${row.id} occurs ${count(referenceIds,row.id)} times.`);for(const row of current)if(count(comparisonIds,row.id)!==1)errors.push(`Comparison row ${row.id} occurs ${count(comparisonIds,row.id)} times.`);
 const total=(rows:CbdMaterialRow[])=>rows.reduce((sum,row)=>sum+(row.extended??0),0),byId=(rows:CbdMaterialRow[])=>new Map(rows.map(row=>[row.id,row])),refMap=byId(reference),curMap=byId(current),referenceTotal=total(reference),comparisonTotal=total(current),coveredReferenceTotal=referenceIds.reduce((sum,id)=>sum+(refMap.get(id)?.extended??0),0),coveredComparisonTotal=comparisonIds.reduce((sum,id)=>sum+(curMap.get(id)?.extended??0),0);
 if(Math.abs(referenceTotal-coveredReferenceTotal)>tolerance)errors.push('Reference material total changed during matching.');if(Math.abs(comparisonTotal-coveredComparisonTotal)>tolerance)errors.push('Comparison material total changed during matching.');
 return{valid:!errors.length,errors,referenceTotal,comparisonTotal,coveredReferenceTotal,coveredComparisonTotal};
}
