import {readTabularWorkbook} from '../spreadsheet';
import {normalizeHeader,normalizeText} from './normalize';
import type {CbdMaterialRow,CbdStyle,ComparisonSide,CbdSummary,UploadedCbd} from './types';

const wanted:{key:string;aliases:string[]}[]=[
  {key:'group',aliases:['GROUPOF','GROUP']},{key:'material',aliases:['MATERIAL','ITEM']},{key:'size',aliases:['SIZE','WIDTH']},
  {key:'unit',aliases:['UNIT']},{key:'cost',aliases:['COSTPERUNIT','UNITCOST']},{key:'usage',aliases:['USAGE']},
  {key:'loss',aliases:['LOSS']},{key:'extended',aliases:['EXTENDEDCOST','AMOUNT']},{key:'remark',aliases:['REMARK','REMARKS']},
];
const num=(v:unknown)=>{if(typeof v==='number'&&Number.isFinite(v))return v;const n=Number(String(v??'').replace(/[$,%\s,]/g,''));return Number.isFinite(n)?(/%/.test(String(v))?n/100:n):undefined};
const findHeader=(rows:unknown[][])=>{for(let r=0;r<Math.min(rows.length,30);r++){const cells=rows[r].map(normalizeHeader),map:Record<string,number>={};for(const field of wanted){const col=cells.findIndex(c=>field.aliases.some(a=>c===a||c.includes(a)));if(col>=0)map[field.key]=col}if(['group','material','unit','cost','usage','loss','extended','remark'].filter(k=>map[k]!==undefined).length>=7)return{row:r,map}}return null};
const styleName=(rows:unknown[][],sheet:string,file:string)=>{for(let r=0;r<Math.min(rows.length,30);r++)for(let c=0;c<(rows[r]?.length||0);c++){const text=normalizeText(rows[r][c]);if(/MODEL\s*NAME|STYLE(?:\s*NAME)?/.test(text)){const right=String(rows[r][c+1]??'').trim();if(right)return right}}
  const repeated=new Map<string,number>();rows.slice(0,4).flatMap(row=>row||[]).map(v=>String(v??'').trim()).filter(v=>v.length>3).forEach(v=>repeated.set(v,(repeated.get(v)||0)+1));const title=[...repeated.entries()].filter(([v,n])=>n>=2&&!/FLY RACING CBD SHEET|DATE|GROUP|MATERIAL|COST|USAGE|REMARK/i.test(v)).sort((a,b)=>b[1]-a[1])[0]?.[0];if(title)return title;
  const candidates=rows.slice(0,8).flatMap(row=>row||[]).map(v=>String(v??'').trim()).filter(v=>v.length>4&&!/GROUP|MATERIAL|COST|USAGE|REMARK/i.test(v));return candidates.sort((a,b)=>b.length-a.length)[0]||sheet||file.replace(/\.xlsx?$/i,'')};
const summaryKey=(text:string):keyof CbdSummary|undefined=>/TOTAL\s*MATERIAL/.test(text)?'totalMaterialCost':/LABOR\s*COST/.test(text)?'laborCost':/OVERHEAD/.test(text)?'overhead':/PROFIT/.test(text)?'profit':/FOB\s*(?:PRICE)?/.test(text)?'fob':/CBD\s*MATERIAL\s*\/\s*FOB/.test(text)?'materialFob':/ERP.*(?:PRE|사전)/.test(text)?'erpMaterial':/DIFFERENCE\s*RATE/.test(text)?'differenceRate':/^DIFFERENCE/.test(text)?'difference':undefined;
export async function parseCbdFiles(files:File[],side:ComparisonSide):Promise<{files:UploadedCbd[];styles:CbdStyle[];errors:string[]}>{const parsedFiles:UploadedCbd[]=[],styles:CbdStyle[]=[],errors:string[]=[];for(const file of files){try{const sheets=await readTabularWorkbook(file),styleIds:string[]=[];for(const sheet of sheets){const header=findHeader(sheet.rows);if(!header)continue;let group='',order=0;const materials:CbdMaterialRow[]=[],summary:CbdSummary={},groupOrder:string[]=[];for(let r=header.row+1;r<sheet.rows.length;r++){const row=sheet.rows[r]||[],material=String(row[header.map.material]??'').trim(),groupCell=String(row[header.map.group]??'').trim(),joined=normalizeText(row.join(' '));const sk=summaryKey(joined);if(sk){summary[sk]=num(row[header.map.extended]??row.find(v=>num(v)!==undefined));continue}if(!material||/^REFERENCES?$|SUBTOTAL|TOTAL MATERIAL|INTERNAL USE ONLY/i.test(material))continue;if(groupCell&&!/SUBTOTAL|TOTAL/i.test(groupCell)){group=groupCell;if(!groupOrder.includes(group))groupOrder.push(group)}if(!group)group='NEEDS REVIEW';materials.push({id:`${file.name}:${sheet.name}:${r}`,group,material,size:String(row[header.map.size]??''),unit:String(row[header.map.unit]??''),cost:num(row[header.map.cost]),usage:num(row[header.map.usage]),loss:num(row[header.map.loss]),extended:num(row[header.map.extended]),remark:String(row[header.map.remark]??''),width:String(row[header.map.size]??''),order:order++})}if(!materials.length)continue;const id=`${side}:${file.name}:${sheet.name}`,style:CbdStyle={id,side,fileName:file.name,sheetName:sheet.name,styleName:styleName(sheet.rows,sheet.name,file.name),materials,summary,groupOrder};styles.push(style);styleIds.push(id)}parsedFiles.push({id:`${side}:${file.name}:${file.lastModified}`,name:file.name,size:file.size,lastModified:file.lastModified,side,styleIds})}catch(error){errors.push(`${file.name}: ${error instanceof Error?error.message:'파싱 실패'}`)}}return{files:parsedFiles,styles,errors}}
