import {describe,it,expect} from 'vitest';
import {assignMaterialMatches,validateMaterialMatchIntegrity} from './matcher';
import {groupAmounts,resolveGroup,relationPresentation,unitChanged} from './groups';
import type {CbdMaterialRow} from './types';
const row=(id:string,material:string,unit='PCS',group='OUTSHELL',extended=1):CbdMaterialRow=>({id,material,unit,group,extended,cost:2,usage:.5,size:'',width:'',remark:'',order:0});
describe('context identity and independent assignment',()=>{
 const pairs=[['HANG TAG FLY RACING 26 RAYCE PANT','HANG TAG FLY RACING 25 RAYCE JERSEY','PCS','SET'],['FLY RACING MAIN BUCKLE','FLY RACING MAIN BUCKLE SET','PCS','SET'],['NYLON WEBBING (30M/M)','NEW - NYLON WEBBING (30M/M) P','YD','M'],['VT_SIZE WOVEN LABEL FLY RACING 26','SIZE WOVEN LABEL FLY RACING 26','PCS','SET']];
 it.each(pairs)('matches %s with same and changed units',(a,b,u,v)=>{for(const targetUnit of [u,v]){const refs=[row('r',a,u)],curr=[row('c',b,targetUnit,'TRIMS')],cs=assignMaterialMatches(refs,curr);expect(cs).toHaveLength(1);expect(cs[0].currentRowId).toBe('c');expect(cs[0].referenceRowIds).toEqual(['r']);expect(unitChanged(refs,curr[0])).toBe(u!==targetUnit)}});
 it('does not merge adjacent buckle and webbing',()=>{const refs=pairs.slice(1,3).map((p,i)=>row(`r${i}`,p[0],p[2])),curr=pairs.slice(1,3).map((p,i)=>row(`c${i}`,p[1],p[3]));const cs=assignMaterialMatches(refs,curr);expect(cs).toHaveLength(2);expect(cs.every(c=>c.relationType==='one-to-one')).toBe(true);expect(validateMaterialMatchIntegrity(refs,curr,cs).valid).toBe(true)});
 it.each([['NYLON WEBBING 25MM','NYLON WEBBING 30MM'],['FLY MAIN BUCKLE','FLY SQUARE BUCKLE'],['BUCKLE AB123','BUCKLE AB456'],['LABEL #AF132 A01','LABEL #AF132 A02'],['WEBBING LEFT 30MM','WEBBING RIGHT 30MM'],['HANG TAG 3 PAGES 1 EYELET','HANG TAG 4 PAGES 1 EYELET']])('rejects %s / %s',(a,b)=>expect(assignMaterialMatches([row('r',a)],[row('c',b)]).some(c=>c.referenceRowIds.length&&c.currentRowId)).toBe(false));
 it('retains ambiguous hang tags for review',()=>{const cs=assignMaterialMatches([row('r',pairs[0][0])],[row('c',pairs[0][1]),row('c2','HANG TAG FLY RACING 24 RAYCE JERSEY')]);expect(cs.some(c=>c.status==='REVIEW')).toBe(true);expect(cs.some(c=>c.referenceRowIds.length&&c.currentRowId)).toBe(false)});
});
describe('group reclassification conserves source money',()=>{
 it('moves 0.1731 from OUTSHELL to TRIMS and preserves originals through repeated edits',()=>{const refs=[row('r1','ES#N FD 160D (PU 1TIME)','YD','OUTSHELL',.1511),row('r2','POLY TASLAN PA COATED (WRCO) (CN)','YD','OUTSHELL',.022),row('r3','OUTSHELL BALANCE','YD','OUTSHELL',8.2368),row('r4','TRIMS BALANCE','PCS','TRIMS',3.754),row('r5','OTHER','PCS','LABEL & PACKAGING',1.4844)];const curr=refs.map((r,i)=>({...r,id:`c${i+1}`,group:i<2?'TRIMS':r.group,extended:[.1,.02,7.9605,3.5406,1.2563][i]}));const cs=assignMaterialMatches(refs,curr);expect(cs).toHaveLength(5);const totals=groupAmounts(cs,refs,curr);expect(totals.OUTSHELL.reference).toBeCloseTo(8.2368,6);expect(totals.TRIMS.reference).toBeCloseTo(3.9271,6);expect(totals.TRIMS.comparison).toBeCloseTo(3.6606,6);expect(validateMaterialMatchIntegrity(refs,curr,cs).valid).toBe(true);expect(validateMaterialMatchIntegrity(refs,curr,cs).referenceTotal).toBeCloseTo(13.6483,6);expect(validateMaterialMatchIntegrity(refs,curr,cs).comparisonTotal).toBeCloseTo(12.8774,6);const c=cs.find(c=>c.referenceRowIds.includes('r1'))!;expect(relationPresentation(c,[refs[0]],curr[0],true).status).toContain('그룹 변경 (OUTSHELL → TRIMS)');const moved=resolveGroup({...c,finalGroup:'OUTSHELL',manualGroupOverride:true},refs,curr),redo=resolveGroup({...moved,finalGroup:'TRIMS'},refs,curr);expect(redo.referenceOriginalGroup).toBe('OUTSHELL');expect(redo.comparisonOriginalGroup).toBe('TRIMS');expect(redo.groupAssignmentSource).toBe('manual');expect(relationPresentation(redo,[refs[0]],curr[0],true).status).toContain('수동 그룹 변경 (OUTSHELL → TRIMS)');expect(groupAmounts(cs.map(x=>x.id===c.id?moved:x),refs,curr).OUTSHELL.reference).toBeCloseTo(8.3879,6);expect(groupAmounts(cs.map(x=>x.id===c.id?redo:x),refs,curr)).toEqual(totals)});
});
