export type ComparisonSide='reference'|'current';
export type MatchStatus='Exact'|'Normalized'|'Alias'|'Manual'|'reference-only'|'current-only'|'duplicate'|'review';
export interface CbdMaterialRow {id:string;group:string;material:string;size:string;unit:string;cost?:number;usage?:number;loss?:number;extended?:number;remark:string;width:string;order:number}
export type FobEvidence='explicit'|'ratio-derived'|'review-required';
export interface CbdSummary {remarks?:Record<string,string>;totalMaterialCost?:number;laborCost?:number;overhead?:number;profit?:number;finalFob?:number;materialToFobRatio?:number;erpMaterial?:number;difference?:number;differenceRate?:number;fobEvidence?:FobEvidence;fobValidation?:'matched'|'mismatch'|'not-available';calculatedFob?:number}
export interface CbdStyle {id:string;side:ComparisonSide;fileName:string;sheetName:string;styleName:string;sourceDate?:string;materials:CbdMaterialRow[];summary:CbdSummary;groupOrder:string[];groupTotals?:Record<string,number>}
export interface UploadedCbd {id:string;name:string;size:number;lastModified:number;side:ComparisonSide;styleIds:string[]}
export interface StyleMatch {id:string;referenceId?:string;currentId?:string;method:string;confidence:number;status:MatchStatus;excluded?:boolean}
export type MaterialStatus='MATCH'|'EXACT'|'CODE MATCH'|'NORMALIZED'|'TOKEN MATCH'|'SIMILAR'|'NAME CHANGED'|'GROUP CHANGED'|'CURRENT ONLY'|'REFERENCE ONLY'|'REVIEW'|'MANUAL'|'MERGED N:1';
export interface MaterialMatchEvidence {score:number;method:'Context Match'|'Exact'|'Code Match'|'Normalized'|'Token Match'|'Similar'|'Merged N:1'|'Needs Review';matchedCodes:string[];matchedTokens:string[];ignoredReference:string[];ignoredComparison:string[];groupAssessment:string;unitAssessment:string;reason:string}
export interface MaterialMatch {id:string;referenceId?:string;currentId?:string;finalGroup:string;referenceGroup?:string;currentGroup?:string;method:string;confidence:number;status:MaterialStatus}
export type MaterialMatchCluster={id:string;referenceRowIds:string[];currentRowId:string|null;currentRowIds?:string[];relationType:'one-to-one'|'many-to-one'|'one-to-many';matchSource:'auto'|'manual';manualLocked?:boolean;manualOrder?:number;finalGroup:string;referenceOriginalGroup?:string;comparisonOriginalGroup?:string;effectiveGroup?:string;groupChangedFrom?:string;groupChangedTo?:string;groupChangeSource?:'manual'|'automatic';groupAssignmentSource?:'comparison'|'manual'|'referenceFallback';manualGroupOverride?:boolean;status:MaterialStatus;confidence:number;evidence?:MaterialMatchEvidence};
export interface MaterialMatchSet {styleMatchId:string;clusters:MaterialMatchCluster[];matches?:MaterialMatch[];matcherVersion?:number}
export interface ComparisonState {version:number;matcherVersion?:number;referenceSeason:string;currentSeason:string;files:UploadedCbd[];styles:CbdStyle[];styleMatches:StyleMatch[];materialMatches:MaterialMatchSet[];step:1|2|3|4|5;activeMatchId?:string;savedAt?:string;history?:{past:ComparisonState[];future:ComparisonState[]}}
export interface ComparisonFinancials {referenceFob?:number;comparisonFob?:number;referenceMaterialTotal?:number;comparisonMaterialTotal?:number;referenceMaterialToFobRatio?:number;comparisonMaterialToFobRatio?:number;referenceFobEvidence:FobEvidence;comparisonFobEvidence:FobEvidence}
