import {chromium,webkit} from 'playwright';
import ExcelJS from 'exceljs';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const dir=await mkdtemp(join(tmpdir(),'cbd-comparison-'));
async function fixture(name,styles,season){const wb=new ExcelJS.Workbook();for(const style of styles){const ws=wb.addWorksheet(style);ws.addRow(['Model Name',style]);ws.addRow([]);ws.addRow(['Group of','Material','Size','Unit','Cost per Unit','Usage','Loss','Extended Cost','Remark']);ws.addRow(['OUTSHELL',`PRINTED FLY RACING ${season} ${style}+JX-12 (POLY)`,'58','YD',2,1,.05,{formula:'E4*F4*(1+G4)'},'BODY']);ws.addRow(['TRIMS','ZIPPER','','PCS',1,.5,.05,{formula:'E5*F5*(1+G5)'},'']);ws.addRow(['OUTSHELL SUBTOTAL','','','','','','',{formula:'SUM(H4:H5)'},'']);ws.addRow(['','Total material cost','','','','','',2.625,'']);ws.addRow(['','FOB PRICE','','','','','',10,''])}const path=join(dir,name);await writeFile(path,Buffer.from(await wb.xlsx.writeBuffer()));return path}
const ref1=await fixture('27 MX.xlsx',['27 RAYCE JERSEY'],'26'),ref2=await fixture('27 BMX.xlsx',['27 BMX JERSEY'],'26'),cur=await fixture('28 ALL.xlsx',['RAYCE JERSEY','BMX JERSEY'],'26');
for(const engine of [chromium,webkit]){const browser=await engine.launch({headless:true}),page=await browser.newPage();await page.goto('http://127.0.0.1:5175/');await page.getByRole('button',{name:'CBD 비교'}).click();await page.locator('input[type=file]').nth(0).setInputFiles([ref1,ref2]);await page.getByText('2 files · 2 styles',{exact:true}).waitFor();await page.locator('input[type=file]').nth(1).setInputFiles(cur);await page.getByRole('heading',{name:'Review Style Matches'}).waitFor();await page.getByText('1 file · 2 styles',{exact:true}).waitFor();await page.getByRole('button',{name:'Confirm Style Matches'}).click();await page.getByRole('heading',{name:'Review Material Matches'}).waitFor();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export All Styles'}).click();const item=await download;if(!item.suggestedFilename().endsWith('.xlsx'))throw new Error('comparison download missing');await page.waitForTimeout(900);await page.reload();await page.getByRole('heading',{name:'Review Material Matches'}).waitFor();await browser.close();console.log(`${engine.name()}: comparison upload, matching, export, IndexedDB restore PASS`)}
