import {readFile,writeFile} from 'node:fs/promises';
import ExcelJS from 'exceljs';
import {parseCbdFiles} from '../src/comparison/parser';
import {matchMaterials,matchStyles} from '../src/comparison/matcher';
import {buildComparisonWorkbook} from '../src/comparison/exporter';
import type {ComparisonState} from '../src/comparison/types';

const referencePaths=['reference/FLY RACING 27 BMX JERSEY CBD 2025.10.17.xlsx','reference/FLY RACING 27 BMX PANT CBD CHART 2025.10.17.xlsx','reference/FLY RACING 27 MX GLOVE CBD 2025.10.17.xlsx','reference/FLY RACING 27 MX JERSEY CBD 2025.10.17.xlsx','reference/FLY RACING 27 MX PANT CBD CHART 2025.10.17.xlsx'];
const comparisonPaths=['reference/FLY RACING 28 MX BMX JERSEY CBD SHEET (내부) 2026.09.02.xlsx','reference/FLY RACING 28 MX BMX PANT CBD SHEET (내부) 2026.09.02.xlsx','reference/FLY RACING 28 MX GLOVE CBD CBD SHEET (내부) 2026.09.02 REV1.xlsx'];
const files=async(paths:string[])=>Promise.all(paths.map(async path=>new File([await readFile(path)],path.split('/').at(-1)!)));
const reference=await parseCbdFiles(await files(referencePaths),'reference'),comparison=await parseCbdFiles(await files(comparisonPaths),'current'),styles=[...reference.styles,...comparison.styles],styleMatches=matchStyles(styles),paired=styleMatches.filter(match=>match.referenceId&&match.currentId),materialMatches=paired.map(match=>matchMaterials(match,styles));
const state:ComparisonState={version:2,referenceSeason:'27',currentSeason:'28',files:[],styles,styleMatches,materialMatches,step:5};
const all=buildComparisonWorkbook(state),rayce=paired.find(match=>styles.find(item=>item.id===match.currentId)?.styleName.endsWith('RAYCE PANT'));if(!rayce)throw new Error('RAYCE PANT pair not found');const single=buildComparisonWorkbook(state,{stylePairIds:[rayce.id]});
for(const [path,book] of [['/tmp/CBD_Comparison_27_vs_28_all.xlsx',all],['/tmp/CBD_Comparison_27_vs_28_RAYCE_PANT.xlsx',single]] as const)await writeFile(path,Buffer.from(await book.xlsx.writeBuffer()));
const failures:string[]=[],fobRows:Record<string,{reference?:number;comparison?:number;ratio?:number;validation?:string}>={};
for(const match of paired){const ref=styles.find(item=>item.id===match.referenceId)!,cur=styles.find(item=>item.id===match.currentId)!;fobRows[cur.styleName]={reference:ref.summary.finalFob,comparison:cur.summary.finalFob,ratio:cur.summary.materialToFobRatio,validation:cur.summary.fobValidation};const sheet=all.getWorksheet(cur.styleName.slice(0,31));if(!sheet)continue;const summary=all.getWorksheet('STYLE MATCH')!,summaryRow=summary.getColumn(4).values.findIndex(value=>value===cur.styleName);if(ref.summary.finalFob!==undefined&&sheet.getCell('B7').result!==summary.getCell(summaryRow,9).value||cur.summary.finalFob!==undefined&&sheet.getCell('C7').result!==summary.getCell(summaryRow,10).value)failures.push(`${cur.styleName}: STYLE MATCH FOB mismatch`);if(ref.summary.finalFob!==undefined&&cur.summary.finalFob!==undefined&&(sheet.getCell('D7').formula!=='C7-B7'||sheet.getCell('E7').formula!=='IF(B7=0,"",D7/B7)'))failures.push(`${cur.styleName}: FOB formula mismatch`);if(sheet.getCell('A5').master.address!=='A5'||sheet.getCell('E5').master.address!=='A5')failures.push(`${cur.styleName}: top title merge mismatch`);for(const cell of ['B6','C6','D6','E6','B7','C7','D7','E7'])if(sheet.getCell(cell).alignment.horizontal!=='right')failures.push(`${cur.styleName}: ${cell} alignment mismatch`);if(typeof sheet.autoFilter==='string'||sheet.autoFilter?.to.column!==15)failures.push(`${cur.styleName}: filter mismatch`)}
const formulas=all.worksheets.flatMap(sheet=>{const values:string[]=[];sheet.eachRow(row=>row.eachCell(cell=>{if(cell.formula)values.push(cell.formula)}));return values});if(formulas.some(value=>/#VALUE!|#REF!|#DIV\/0!|#NAME\?|OFFSET|INDIRECT|SUMPRODUCT/i.test(value)))failures.push('invalid or complex formula found');
if(failures.length)throw new Error(failures.join('\n'));console.log(JSON.stringify({outputs:['/tmp/CBD_Comparison_27_vs_28_all.xlsx','/tmp/CBD_Comparison_27_vs_28_RAYCE_PANT.xlsx'],parsed:{reference:reference.styles.length,comparison:comparison.styles.length,paired:paired.length},raycePant:Object.entries(fobRows).find(([name])=>name.endsWith('RAYCE PANT'))?.[1],missingExplicitComparisonFob:Object.entries(fobRows).filter(([,value])=>value.comparison===undefined).map(([name])=>name),fobRows,formulaCount:formulas.length,failures},null,2));
