import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, FileSpreadsheet, RotateCcw, Upload, Undo2, X } from 'lucide-react';
import { GROUPS, extendedCost, visibleGroups, type AppSettings, type CbdGroup, type ClassificationDictionary, type Material, type StyleData } from './types';
import { aggregate, parseBomFile, rowsFromSheet, splitMaterial } from './parser';
import type { ColumnMapping } from './types';
import { downloadBuyerExcel } from './exporter';
import { exactFobMatch, fobCandidates, parseFobFile, type FobRecord } from './fob';
import { dictionaryKeys } from './classifier';

const STORE='cbd-generator-work-v1', DICT='cbd-generator-dictionary-v1';
const initialSettings:AppSettings={exchangeRate:900,defaultLoss:.05};
const clone=<T,>(v:T):T=>structuredClone(v);
const money=(n:number)=>`$${n.toFixed(4)}`;

export default function App(){
  const restored=useMemo(()=>{try{return JSON.parse(localStorage.getItem(STORE)||'null')}catch{return null}},[]);
  const [styles,setStyles]=useState<StyleData[]>(restored?.styles||[]),[active,setActive]=useState(restored?.active||'');
  const [settings,setSettings]=useState<AppSettings>(restored?.settings||initialSettings),[selected,setSelected]=useState<Set<string>>(new Set());
  const [dict,setDict]=useState<ClassificationDictionary>(()=>{try{return JSON.parse(localStorage.getItem(DICT)||'{}')}catch{return {}}});
  const [history,setHistory]=useState<StyleData[][]>([]),[notice,setNotice]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set());
  const [scope,setScope]=useState('selected'),[target,setTarget]=useState('cost'),[operation,setOperation]=useState('base-percent'),[bulkValue,setBulkValue]=useState(5),[preview,setPreview]=useState<number|null>(null);
  const [fobs,setFobs]=useState<FobRecord[]>([]); const dictInput=useRef<HTMLInputElement>(null);
  const [mapping,setMapping]=useState<{file:string;sheet:string;rows:unknown[][];headerRow:number;columns:ColumnMapping}|null>(null);
  const style=styles.find(s=>s.id===active)||styles[0];
  useEffect(()=>{if(!active&&styles[0])setActive(styles[0].id)},[styles,active]);
  useEffect(()=>localStorage.setItem(STORE,JSON.stringify({styles,active,settings})),[styles,active,settings]);
  useEffect(()=>localStorage.setItem(DICT,JSON.stringify(dict)),[dict]);
  const commit=(fn:(draft:StyleData[])=>void)=>{setHistory(h=>[...h.slice(-19),clone(styles)]);setStyles(prev=>{const next=clone(prev);fn(next);return next});};
  const updateMaterial=(id:string,patch:Partial<Material>)=>commit(ds=>{const m=ds.find(s=>s.id===style?.id)?.materials.find(x=>x.id===id);if(m)Object.assign(m,patch)});
  const uploadBom=async(files:FileList|null)=>{if(!files)return;let added:StyleData[]=[];for(const file of Array.from(files)){try{const result=await parseBomFile(file,settings,dict);if(result.unmapped){setMapping({file:file.name,sheet:result.unmapped.sheet,rows:result.unmapped.rows,headerRow:0,columns:{}});setNotice(`${file.name}: 컬럼을 직접 지정해 주세요.`);continue;}added=added.concat(result.styles)}catch{setNotice(`${file.name}을 읽지 못했습니다.`)}}if(added.length){commit(d=>d.push(...added));setActive(added[0].id);setNotice(`${added.length}개 스타일을 브라우저에서 분석했습니다.`)}};
  const changeGroup=(m:Material,g:CbdGroup)=>{updateMaterial(m.id,{group:g,included:g!=='EXCLUDE'});const additions={...dict};dictionaryKeys(m.sources[0]).forEach(k=>additions[k]=g);setDict(additions)};
  const materialsForScope=(s:StyleData)=>s.materials.filter(m=>scope==='all'||(scope==='selected'&&selected.has(m.id))||(scope==='group'&&style&&m.group===style.materials.find(x=>selected.has(x.id))?.group)||m.group===scope);
  const projected=(apply=false)=>{if(!style)return 0;let total=0;const ids=new Set(materialsForScope(style).map(m=>m.id));const mutate=(m:Material)=>{if(!ids.has(m.id))return;const v=Number(bulkValue);if(target==='loss'){m.additionalLoss=operation==='reset'?settings.defaultLoss:operation==='current-percent'?m.additionalLoss*(1+v/100):operation==='base-percent'?settings.defaultLoss*(1+v/100):v/100;return;}const base=target==='cost'?m.baseCost:m.baseUsage,current=target==='cost'?m.adjustedCost:m.adjustedUsage;const next=operation==='reset'?base:operation==='set'?v:operation==='base-percent'?base*(1+v/100):current*(1+v/100);if(target==='cost')m.adjustedCost=next;else m.adjustedUsage=next;};
    if(apply)commit(ds=>ds.find(s=>s.id===style.id)!.materials.forEach(mutate)); const copy=clone(style.materials);copy.forEach(mutate);total=copy.filter(m=>m.included&&visibleGroups.includes(m.group)).reduce((s,m)=>s+extendedCost(m),0);return total;};
  const internal=useMemo(()=>{if(!style)return null;const all=style.materials.reduce((s,m)=>s+m.baseCost*m.baseUsage,0), visible=style.materials.filter(m=>m.included&&visibleGroups.includes(m.group)).reduce((s,m)=>s+(m.group==='SEWING THREAD'?0:extendedCost(m)),0)+(style.threadSubtotal??style.materials.filter(m=>m.group==='SEWING THREAD'&&m.included).reduce((s,m)=>s+m.baseCost*m.baseUsage,0));const sumType=(rx:RegExp)=>style.materials.filter(m=>m.sources.some(r=>rx.test(r.materialType))).reduce((s,m)=>s+m.baseCost*m.baseUsage,0);return{all,visible,sewing:sumType(/봉제공임/),packing:sumType(/포장공임/),special:sumType(/특수공임|기타공임/),review:style.materials.filter(m=>m.group==='NEEDS REVIEW').length,excluded:style.materials.filter(m=>!m.included||m.group==='EXCLUDE').length}},[style]);
  const exportStyles=async(list:StyleData[])=>{const review=list.reduce((n,s)=>n+s.materials.filter(m=>m.group==='NEEDS REVIEW').length,0);if(review&&!confirm(`미분류 항목이 ${review}개 있습니다. 계속 다운로드할까요?`))return;await downloadBuyerExcel(list,list.length===1?`${list[0].name}_CBD.xlsx`:'Buyer_CBD_All_Styles.xlsx')};
  const uploadFob=async(file?:File)=>{if(!file)return;const rec=await parseFobFile(file);setFobs(rec);commit(ds=>ds.forEach(s=>{const hit=exactFobMatch(s.name,rec);if(hit){s.finalFob=hit.fob;s.fobMatch=hit.style}}));setNotice(`FOB ${rec.length}건을 읽고 정확히 일치하는 스타일을 연결했습니다.`)};
  const proportional=()=>{if(!style?.materialTarget)return;const chosen=materialsForScope(style).filter(m=>m.included&&visibleGroups.includes(m.group)&&m.group!=='SEWING THREAD');const current=chosen.reduce((s,m)=>s+extendedCost(m),0),fixed=(internal?.visible||0)-current,factor=(style.materialTarget-fixed)/current;if(!Number.isFinite(factor)||factor<=0)return setNotice('선택 범위와 목표액을 확인하세요.');if(confirm(`선택 자재 단가를 ${(factor*100).toFixed(2)}% 비율로 조정할까요?`))commit(ds=>ds.find(s=>s.id===style.id)!.materials.filter(m=>chosen.some(c=>c.id===m.id)).forEach(m=>m.adjustedCost*=factor));};
  const mappingDialog=mapping&&<MappingDialog value={mapping} onChange={setMapping} onCancel={()=>setMapping(null)} onApply={()=>{if(mapping.columns.item===undefined||((mapping.columns.usage===undefined)&&(mapping.columns.netUsage===undefined))||((mapping.columns.convertedPrice===undefined)&&(mapping.columns.rawPrice===undefined)))return setNotice('Item, Usage(또는 정소요량), 단가(또는 환산단가)는 필수입니다.');const rows=rowsFromSheet(mapping.rows,mapping.columns,mapping.headerRow,{file:mapping.file,sheet:mapping.sheet},settings);const name=mapping.file.replace(/\.(xls|xlsx)$/i,'').replace(/\bBOM\b/ig,'').trim();const s:StyleData={id:`${mapping.file}:${mapping.sheet}:${Date.now()}`,name:name||mapping.sheet,sourceFile:mapping.file,sourceSheet:mapping.sheet,materials:aggregate(rows,settings.defaultLoss,dict),laborRemark:'It also includes the listed special process and packing costs in the factory.'};commit(ds=>ds.push(s));setActive(s.id);setMapping(null);setNotice('수동 컬럼 매핑으로 스타일을 분석했습니다.')}}/>;
  if(!styles.length)return <main><header className="hero"><div className="brand">CBD<span>Chart Generator</span></div><h1>BOM에서 Buyer CBD까지,<br/>브라우저 안에서 안전하게.</h1><p>원가 파일은 업로드 서버나 외부 API로 전송되지 않습니다.</p></header><section className="start-card"><h2>새 작업 시작</h2><div className="settings"><label>KRW fallback 환율<input type="number" value={settings.exchangeRate} onChange={e=>setSettings({...settings,exchangeRate:+e.target.value})}/></label><label>기본 CBD 추가 Loss (%)<input type="number" value={settings.defaultLoss*100} onChange={e=>setSettings({...settings,defaultLoss:+e.target.value/100})}/></label></div><label className="drop"><Upload/><b>BOM Excel 파일 선택</b><span>.xls / .xlsx · 여러 파일 동시 선택 가능</span><input type="file" multiple accept=".xls,.xlsx" onChange={e=>uploadBom(e.target.files)}/></label>{notice&&<p className="notice">{notice}</p>}</section>{mappingDialog}</main>;
  return <div className="app"><aside><div className="brand small">CBD<span>Chart Generator</span></div><button className="upload"><Upload size={16}/> BOM 추가<input type="file" multiple accept=".xls,.xlsx" onChange={e=>uploadBom(e.target.files)}/></button><h3>스타일 <em>{styles.length}</em></h3>{styles.map(s=><button className={`style ${s.id===style?.id?'active':''}`} onClick={()=>setActive(s.id)} key={s.id}><span>{s.name}</span><small>{s.materials.some(m=>m.group==='NEEDS REVIEW')?'검토 필요':'준비됨'}</small></button>)}<div className="side-bottom"><label className="upload ghost"><FileSpreadsheet size={15}/> FOB 파일<input type="file" accept=".xls,.xlsx" onChange={e=>uploadFob(e.target.files?.[0])}/></label><button onClick={()=>{if(confirm('모든 작업 데이터를 초기화할까요?')){localStorage.removeItem(STORE);setStyles([])}}}><X size={15}/> 전체 초기화</button></div></aside>{mappingDialog}
  <section className="workspace"><header className="top"><div><input className="title" value={style.name} onChange={e=>commit(ds=>{ds.find(s=>s.id===style.id)!.name=e.target.value})}/><p>{style.sourceFile} · {style.sourceSheet}</p></div><div className="actions"><button disabled={!history.length} onClick={()=>{const prev=history.at(-1);if(prev){setStyles(prev);setHistory(h=>h.slice(0,-1))}}}><Undo2 size={16}/> Undo</button><button onClick={()=>exportStyles([style])}><Download size={16}/> 현재 스타일</button><button className="primary" onClick={()=>exportStyles(styles)}><Download size={16}/> 전체 Excel</button></div></header>
  {notice&&<div className="notice bar">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <div className="summary">{[['BOM Actual Material',internal?.all],['Buyer-visible Material',internal?.visible],['Difference Embedded',(internal?.visible||0)-(internal?.all||0)],['Internal Sewing',internal?.sewing],['Internal Packing',internal?.packing],['Internal Special Process',internal?.special]].map(([k,v])=><div><span>{k}</span><b>{money(Number(v))}</b></div>)}<div className={(style.finalFob||Infinity)<(internal?.visible||0)?'danger':''}><span>Final FOB</span><input type="number" value={style.finalFob??''} placeholder="직접 입력" onChange={e=>commit(ds=>{ds.find(s=>s.id===style.id)!.finalFob=+e.target.value||undefined})}/><small>차액 {style.finalFob?money(style.finalFob-(internal?.visible||0)):'—'}</small></div><div><span>상태</span><b className="badge">검토 {internal?.review} · 제외 {internal?.excluded}</b></div></div>
  {fobs.length>0&&!style.fobMatch&&<div className="match"><b>FOB 유사 후보 (자동 확정하지 않음)</b>{fobCandidates(style.name,fobs).map(f=><button onClick={()=>commit(ds=>{const s=ds.find(x=>x.id===style.id)!;s.finalFob=f.fob;s.fobMatch=f.style})}>{f.style} · ${f.fob}</button>)}</div>}
  <div className="toolbar"><div><b>일괄 조정</b><select value={scope} onChange={e=>setScope(e.target.value)}><option value="selected">선택 항목</option><option value="all">전체</option><option value="group">선택 그룹</option><option>OUTSHELL</option><option>TRIMS</option><option>LABEL & PACKAGING</option></select><select value={target} onChange={e=>setTarget(e.target.value)}><option value="cost">Cost per Unit</option><option value="usage">Usage</option><option value="loss">CBD 추가 Loss</option></select><select value={operation} onChange={e=>setOperation(e.target.value)}><option value="set">값 설정</option><option value="base-percent">원본 대비 % 인상</option><option value="current-percent">현재 값에 % 추가</option><option value="reset">초기화</option></select>{operation!=='reset'&&<input type="number" value={bulkValue} onChange={e=>setBulkValue(+e.target.value)}/>}<button onClick={()=>setPreview(projected())}>미리보기</button><button className="primary" onClick={()=>{projected(true);setPreview(null)}}>적용</button></div><div><label>Buyer-visible Target <input type="number" value={style.materialTarget??''} onChange={e=>commit(ds=>{ds.find(s=>s.id===style.id)!.materialTarget=+e.target.value||undefined})}/></label><button onClick={proportional}>선택 자재 비례 배분</button></div>{preview!==null&&<p>변경 전 {money(internal?.visible||0)} → 변경 후 <b>{money(preview)}</b></p>}</div>
  <div className="table-wrap"><table><thead><tr><th><input type="checkbox" onChange={e=>setSelected(e.target.checked?new Set(style.materials.map(m=>m.id)):new Set())}/></th><th>CBD Group</th><th>Item / Source Structure</th><th>Width</th><th>Unit</th><th>Base Cost</th><th>Adjusted Cost</th><th>Base Usage</th><th>Adjusted Usage</th><th>CBD 추가 Loss</th><th>Extended Cost</th><th>Remark</th><th>Include</th><th></th></tr></thead><tbody>{style.materials.map(m=><tr key={m.id} className={!m.included?'excluded':m.group==='NEEDS REVIEW'?'review':''}><td><input type="checkbox" checked={selected.has(m.id)} onChange={e=>{const n=new Set(selected);e.target.checked?n.add(m.id):n.delete(m.id);setSelected(n)}}/></td><td><select value={m.group} onChange={e=>changeGroup(m,e.target.value as CbdGroup)}>{GROUPS.map(g=><option>{g}</option>)}</select></td><td className="item"><b>{m.item}</b><button className="source" onClick={()=>{const n=new Set(expanded);n.has(m.id)?n.delete(m.id):n.add(m.id);setExpanded(n)}}>{m.sources.length}개 Structure {expanded.has(m.id)?'접기':'보기'}</button>{expanded.has(m.id)&&<ul>{m.sources.map(s=><li>{s.structure}<span>{s.color}</span></li>)}</ul>}</td><td>{m.width}</td><td>{m.unit}</td><td>{m.baseCost.toFixed(4)}</td><td><input className={m.adjustedCost!==m.baseCost?'changed':''} type="number" step=".0001" value={m.adjustedCost} onChange={e=>updateMaterial(m.id,{adjustedCost:+e.target.value})}/></td><td>{m.baseUsage.toFixed(4)}</td><td><input className={m.adjustedUsage!==m.baseUsage?'changed':''} type="number" step=".0001" value={m.adjustedUsage} onChange={e=>updateMaterial(m.id,{adjustedUsage:+e.target.value})}/></td><td><input className={m.additionalLoss!==settings.defaultLoss?'changed':''} type="number" step=".1" value={m.additionalLoss*100} onChange={e=>updateMaterial(m.id,{additionalLoss:+e.target.value/100})}/>%</td><td><b>{m.group==='SPECIAL PROCESS (LIST ONLY)'?'—':money(extendedCost(m))}</b></td><td><textarea value={m.remark} onChange={e=>updateMaterial(m.id,{remark:e.target.value})}/><button className="source" onClick={()=>updateMaterial(m.id,{remark:[m.remark,...m.sources.map(s=>s.structure)].filter(Boolean).join(' / ')})}>Structure를 Remark로 복사</button></td><td><input type="checkbox" checked={m.included} onChange={e=>updateMaterial(m.id,{included:e.target.checked})}/></td><td><button title="원본값으로 초기화" onClick={()=>updateMaterial(m.id,{adjustedCost:m.baseCost,adjustedUsage:m.baseUsage,additionalLoss:settings.defaultLoss})}><RotateCcw size={15}/></button>{m.sources.length>1&&<button title="그룹 분리" onClick={()=>commit(ds=>{const s=ds.find(x=>x.id===style.id)!;s.materials=s.materials.flatMap(x=>x.id===m.id?splitMaterial(x):x)})}>분리</button>}</td></tr>)}</tbody></table></div>
  <footer><div><b>분류 사전</b><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(dict,null,2)],{type:'application/json'}));a.download='cbd-classification-dictionary.json';a.click()}}>JSON 내보내기</button><button onClick={()=>dictInput.current?.click()}>JSON 불러오기</button><input ref={dictInput} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f)setDict(JSON.parse(await f.text()))}}/></div><p>모든 계산은 이 브라우저 안에서 처리됩니다.</p></footer></section></div>;
}

function MappingDialog({value,onChange,onApply,onCancel}:{value:{file:string;sheet:string;rows:unknown[][];headerRow:number;columns:ColumnMapping};onChange:(v:any)=>void;onApply:()=>void;onCancel:()=>void}){
  const fields:[string,string][]=[['structure','Structure'],['materialType','자재구분'],['sequence','원순번/순번'],['itemNo','Item#'],['item','Item *'],['width','Width'],['color','Color'],['unit','Unit'],['netUsage','정소요량'],['bomLoss','BOM 로스율'],['usage','소요량 *'],['currency','Currency'],['rawPrice','단가'],['convertedPrice','환산단가 *'],['amount','금액'],['specialFlag','특수공정'],['remark','비고']];
  const max=Math.max(1,...value.rows.slice(0,30).map(r=>r.length)); const headers=value.rows[value.headerRow]||[];
  return <div className="modal-back"><div className="modal"><h2>컬럼 매핑</h2><p>{value.file} · {value.sheet} — 자동 인식하지 못한 열을 직접 지정하세요.</p><label>헤더 행 <select value={value.headerRow} onChange={e=>onChange({...value,headerRow:+e.target.value})}>{value.rows.slice(0,30).map((_,i)=><option value={i}>{i+1}행</option>)}</select></label><div className="mapping-grid">{fields.map(([key,label])=><label>{label}<select value={value.columns[key]??''} onChange={e=>onChange({...value,columns:{...value.columns,[key]:e.target.value===''?undefined:+e.target.value}})}><option value="">선택 안 함</option>{Array.from({length:max},(_,i)=><option value={i}>{String.fromCharCode(65+i)} · {String(headers[i]??'')}</option>)}</select></label>)}</div><div className="modal-actions"><button onClick={onCancel}>취소</button><button className="primary" onClick={onApply}>이 매핑으로 분석</button></div></div></div>;
}
