import { useEffect, useMemo, useRef, useState } from 'react';
import { BarChart3, Download, FileSpreadsheet, HelpCircle, LayoutDashboard, Redo2, RotateCcw, Settings as SettingsIcon, Undo2, X } from 'lucide-react';
import { GROUPS, extendedCost, roundTo4, totalMaterialCost, type AppSettings, type CbdGroup, type ClassificationDictionary, type Material, type RowStatusDetail, type StyleData } from './types';
import { aggregate, buildErpMaterialAudit, buyerRowsWithoutHierarchyDuplicates, displayStyleName, migrateStoredRollupChildren, parseBomFile, rowsFromSheet, splitMaterial, statusDetails } from './parser';
import type { ColumnMapping } from './types';
import { downloadBuyerExcel, downloadInternalExcel } from './exporter';
import { fobCandidates, matchFob, parseFobFile, type FobRecord } from './fob';
import { dictionaryKeys, migrateStoredPriorityGroups as migratePriorityGroups } from './classifier';
import { clearSavedWork, loadSavedWork, saveWork } from './persistence';
import BomUploader, { isExcelFile } from './BomUploader';
import FobUploader from './FobUploader';

const LEGACY_STORE='cbd-generator-work-v1', LEGACY_DICT='cbd-generator-dictionary-v1';
const initialSettings:AppSettings={exchangeRate:900,defaultLoss:.05};
const clone=<T,>(v:T):T=>structuredClone(v);
const migrateStoredPriorityGroups=(styles:StyleData[],dict:ClassificationDictionary)=>migrateStoredRollupChildren(migratePriorityGroups(styles,dict));
const money=(n:number)=>`$${n.toFixed(4)}`;
const bulkMoney=(n:number)=>`$${n.toFixed(2)}`;
type StyleHistory={past:StyleData[];future:StyleData[]};
type WorkspaceHistory={past:StyleData[][];future:StyleData[][]};
type BulkState={target:string;operation:string;value:number};
const defaultBulkState:BulkState={target:'cost',operation:'base-percent',value:5};

export default function App(){
  const [styles,setStyles]=useState<StyleData[]>([]),[active,setActive]=useState('');
  const [settings,setSettings]=useState<AppSettings>(initialSettings),[selections,setSelections]=useState<Record<string,string[]>>({});
  const [dict,setDict]=useState<ClassificationDictionary>({});
  const [histories,setHistories]=useState<Record<string,StyleHistory>>({}),[notice,setNotice]=useState(''),[expanded,setExpanded]=useState<Set<string>>(new Set());
  const [workspaceHistory,setWorkspaceHistory]=useState<WorkspaceHistory>({past:[],future:[]});
  const [scopes,setScopes]=useState<Record<string,string>>({}),[bulkStates,setBulkStates]=useState<Record<string,BulkState>>({}),[preview,setPreview]=useState<number|null>(null);
  const [resetDialog,setResetDialog]=useState(false),[resetScope,setResetScope]=useState<'current'|'all'>('current'),[resetting,setResetting]=useState(false);
  const [groupFilters,setGroupFilters]=useState<Record<string,string>>({});
  const [fobs,setFobs]=useState<FobRecord[]>([]),[fobFile,setFobFile]=useState<{name:string;size:number;lastModified:number;parsedCount:number}>(),[showFobMatches,setShowFobMatches]=useState(false),[showErp,setShowErp]=useState(false),[statusView,setStatusView]=useState<'review'|'separate'|'excluded'|null>(null); const dictInput=useRef<HTMLInputElement>(null),styleList=useRef<HTMLDivElement>(null);
  const [mapping,setMapping]=useState<{file:string;sheet:string;rows:unknown[][];headerRow:number;columns:ColumnMapping}|null>(null);
  const [restoring,setRestoring]=useState(typeof indexedDB!=='undefined'),[saveStatus,setSaveStatus]=useState(''),[sidebarScrollTop,setSidebarScrollTop]=useState(0);const suspendSave=useRef(false);
  const style=styles.find(s=>s.id===active)||styles[0];
  const selected=useMemo(()=>new Set(style?selections[style.id]||[]:[]),[selections,style]);
  const scope=style?scopes[style.id]||'all':'all';
  const bulkState=style?bulkStates[style.id]||defaultBulkState:defaultBulkState;
  const {target,operation,value:bulkValue}=bulkState;
  const groupFilter=style?groupFilters[style.id]||'all':'all';
  const setSelected=(next:Set<string>)=>{if(style)setSelections(all=>({...all,[style.id]:[...next]}))};
  const setStyleGroupState=(next:string)=>{if(!style)return;setScopes(all=>({...all,[style.id]:next}));setGroupFilters(all=>({...all,[style.id]:next==='selected'||next==='group'?'all':next}))};
  const setBulkState=(patch:Partial<BulkState>)=>{if(style)setBulkStates(all=>({...all,[style.id]:{...(all[style.id]||defaultBulkState),...patch}}))};
  const setTarget=(target:string)=>setBulkState({target}),setOperation=(operation:string)=>setBulkState({operation}),setBulkValue=(value:number)=>setBulkState({value});
  useEffect(()=>{if(!active&&styles[0])setActive(styles[0].id)},[styles,active]);
  useEffect(()=>{if(!restoring&&!styles.length){setScopes({});setBulkStates({})}},[restoring,styles.length]);
  useEffect(()=>{if(typeof indexedDB==='undefined')return;let cancelled=false;(async()=>{try{let saved=await loadSavedWork();if(!saved){try{const legacy=JSON.parse(localStorage.getItem(LEGACY_STORE)||'null'),legacyDict=JSON.parse(localStorage.getItem(LEGACY_DICT)||'{}');if(legacy?.styles)saved={version:1,styles:legacy.styles,active:legacy.active||'',settings:legacy.settings||initialSettings,dict:legacyDict,selections:{},groupFilters:{},fobs:[],scope:'all',target:'cost',operation:'base-percent',bulkValue:5,savedAt:''}}catch{/* ignore invalid legacy data */}}if(saved&&!cancelled){const restoredStyles=migrateStoredPriorityGroups(saved.styles,saved.dict);const restoredScopes=saved.scopes||Object.fromEntries(restoredStyles.map(s=>[s.id,saved.groupFilters?.[s.id]||'all']));if(!saved.scopes&&saved.active)restoredScopes[saved.active]=saved.scope||restoredScopes[saved.active]||'all';const restoredBulkStates=saved.bulkStates||Object.fromEntries(restoredStyles.map(s=>[s.id,{...defaultBulkState}]));if(!saved.bulkStates&&saved.active)restoredBulkStates[saved.active]={target:saved.target||'cost',operation:saved.operation||'base-percent',value:saved.bulkValue??5};const syncedFilters=Object.fromEntries(restoredStyles.map(s=>{const value=restoredScopes[s.id]||'all';return[s.id,value==='selected'||value==='group'?'all':value]}));setStyles(restoredStyles);setActive(saved.active);setSettings(saved.settings);setDict(saved.dict);setSelections(saved.selections||{});setScopes(restoredScopes);setBulkStates(restoredBulkStates);setGroupFilters(syncedFilters);setFobs(saved.fobs||[]);setFobFile(saved.fobFile);setSidebarScrollTop(saved.sidebarScrollTop||0);if(saved.savedAt)setSaveStatus(`자동 저장됨 ${new Date(saved.savedAt).toLocaleTimeString()}`)}localStorage.removeItem(LEGACY_STORE);localStorage.removeItem(LEGACY_DICT)}catch(error){if(!cancelled)setNotice(`저장된 작업을 복원하지 못했습니다: ${error instanceof Error?error.message:'브라우저 저장소 오류'}`)}finally{if(!cancelled)setRestoring(false)}})();return()=>{cancelled=true}},[]);
  useEffect(()=>{if(restoring||typeof indexedDB==='undefined')return;const timer=setTimeout(async()=>{if(suspendSave.current)return;try{const savedStyles=styles.map(s=>({...s,statusDetails:statusDetails(s.materials)}));const savedAt=await saveWork({styles:savedStyles,active,settings,dict,selections,groupFilters,scopes,bulkStates,fobs,fobFile,sidebarScrollTop,scope,target,operation,bulkValue});setSaveStatus(`자동 저장됨 ${new Date(savedAt).toLocaleTimeString()}`)}catch(error){setNotice(`자동 저장 실패: ${error instanceof Error?error.message:'저장 공간을 확인하세요.'}`);setSaveStatus('자동 저장 실패')}},500);return()=>clearTimeout(timer)},[restoring,styles,active,settings,dict,selections,groupFilters,scopes,bulkStates,fobs,fobFile,sidebarScrollTop,scope,target,operation,bulkValue]);
  useEffect(()=>{setExpanded(new Set());setPreview(null);setStatusView(null);setShowErp(false);requestAnimationFrame(()=>{const selected=document.querySelector('.style.active') as HTMLElement|null;selected?.scrollIntoView?.({block:'nearest'})})},[active]);
  useEffect(()=>{if(styleList.current)styleList.current.scrollTop=sidebarScrollTop},[restoring]);
  const commit=(fn:(draft:StyleData[])=>void,styleId=style?.id)=>{if(!styleId)return;const before=styles.find(s=>s.id===styleId);if(!before)return;setWorkspaceHistory({past:[],future:[]});setHistories(h=>({...h,[styleId]:{past:[...(h[styleId]?.past||[]).slice(-19),clone(before)],future:[]}}));setStyles(prev=>{const next=clone(prev);fn(next);return next});};
  const undo=()=>{if(workspaceHistory.past.length){const previous=workspaceHistory.past.at(-1)!;setWorkspaceHistory(h=>({past:h.past.slice(0,-1),future:[clone(styles),...h.future].slice(0,20)}));setHistories(h=>({...h,[style!.id]:{past:h[style!.id]?.past||[],future:[clone(style!)]}}));setStyles(clone(previous));return}if(!style)return;const h=histories[style.id],previous=h?.past.at(-1);if(!previous)return;const current=clone(style);setStyles(ds=>ds.map(s=>s.id===style.id?clone(previous):s));setHistories(all=>({...all,[style.id]:{past:h.past.slice(0,-1),future:[current,...h.future].slice(0,20)}}));};
  const redo=()=>{if(workspaceHistory.future.length){const next=workspaceHistory.future[0];setWorkspaceHistory(h=>({past:[...h.past,clone(styles)].slice(-20),future:h.future.slice(1)}));setHistories(h=>({...h,[style!.id]:{past:h[style!.id]?.past||[],future:[]}}));setStyles(clone(next));return}if(!style)return;const h=histories[style.id],next=h?.future[0];if(!next)return;const current=clone(style);setStyles(ds=>ds.map(s=>s.id===style.id?clone(next):s));setHistories(all=>({...all,[style.id]:{past:[...h.past,current].slice(-20),future:h.future.slice(1)}}));};
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(!(e.ctrlKey||e.metaKey))return;const tag=(e.target as HTMLElement)?.tagName;if(tag==='INPUT'||tag==='TEXTAREA'||tag==='SELECT')return;if(e.key.toLowerCase()==='z'&&!e.shiftKey){e.preventDefault();undo()}else if(e.key.toLowerCase()==='y'||(e.key.toLowerCase()==='z'&&e.shiftKey)){e.preventDefault();redo()}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)});
  const updateMaterial=(id:string,patch:Partial<Material>)=>commit(ds=>{const m=ds.find(s=>s.id===style?.id)?.materials.find(x=>x.id===id);if(m)Object.assign(m,patch)});
  const uploadBom=async(files:File[])=>{if(!files.length)return;const valid=files.filter(isExcelFile),errors=files.filter(file=>!isExcelFile(file)).map(file=>`${file.name}: Excel 파일(.xls 또는 .xlsx)만 업로드할 수 있습니다.`);if(valid.length)setNotice('BOM 파일을 분석하고 있습니다.');let added:StyleData[]=[];for(const file of valid){try{const result=await parseBomFile(file,settings,dict);if(result.unmapped){setMapping({file:file.name,sheet:result.unmapped.sheet,rows:result.unmapped.rows,headerRow:0,columns:{}});errors.push(`${file.name}: 자동으로 컬럼을 찾지 못했습니다.`);continue;}if(!result.styles.length){errors.push(`${file.name}: 가져올 BOM 자재가 없습니다.`);continue;}added=added.concat(result.styles)}catch(error){errors.push(`${file.name}: ${error instanceof Error?error.message:'파일을 읽지 못했습니다.'}`)}}if(added.length){setStyles(d=>[...d,...added]);setActive(added.at(-1)!.id)}setNotice([added.length?`${added.length}개 스타일을 분석했습니다.`:'',...errors].filter(Boolean).join(' '))};
  const changeGroup=(m:Material,g:CbdGroup)=>{updateMaterial(m.id,{group:g,included:g!=='EXCLUDE'});const additions={...dict};dictionaryKeys(m.sources[0]).forEach(k=>additions[k]=g);setDict(additions)};
  const materialsForScope=(s:StyleData)=>s.materials.filter(m=>scope==='all'||(scope==='selected'&&selected.has(m.id))||(scope==='group'&&style&&m.group===style.materials.find(x=>selected.has(x.id))?.group)||m.group===scope);
  const projected=(apply=false)=>{if(!style)return 0;let total=0;const ids=new Set(materialsForScope(style).map(m=>m.id));const mutate=(m:Material)=>{if(!ids.has(m.id))return;const v=Number(bulkValue),baseLoss=m.baseLoss??settings.defaultLoss;if(target==='loss'){m.additionalLoss=operation==='reset'?baseLoss:operation==='current-percent'?m.additionalLoss*(1+v/100):operation==='base-percent'?baseLoss*(1+v/100):v/100;return;}const base=target==='cost'?m.baseCost:m.baseUsage,current=target==='cost'?m.adjustedCost:m.adjustedUsage;const next=operation==='reset'?base:operation==='set'?v:operation==='base-percent'?base*(1+v/100):current*(1+v/100);if(target==='cost')m.adjustedCost=next;else m.adjustedUsage=next;};
    if(apply)commit(ds=>ds.find(s=>s.id===style.id)!.materials.forEach(mutate)); const copy=clone(style.materials);copy.forEach(mutate);total=totalMaterialCost(copy);return total;};
  const runFullAdjustmentReset=()=>{if(!style||resetting)return;setResetting(true);setNotice('일괄조정값을 초기화하고 있습니다.');setTimeout(()=>{const targets=resetScope==='all'?styles:[style],changed=targets.flatMap(s=>s.materials.map(m=>({style:s,material:m,fields:Number(m.adjustedCost!==m.baseCost)+Number(m.adjustedUsage!==m.baseUsage)+Number(m.additionalLoss!==(m.baseLoss??settings.defaultLoss))}))).filter(x=>x.fields);const valueCount=changed.reduce((sum,x)=>sum+x.fields,0),groupCount=new Set(changed.map(x=>`${x.style.id}:${x.material.group}`)).size;if(!valueCount){setNotice('초기화할 조정값이 없습니다.');setResetDialog(false);setResetting(false);return}const reset=(items:StyleData[])=>items.forEach(s=>s.materials.forEach(m=>{m.adjustedCost=m.baseCost;m.adjustedUsage=m.baseUsage;m.additionalLoss=m.baseLoss??settings.defaultLoss}));if(resetScope==='all'){setWorkspaceHistory(h=>({past:[...h.past,clone(styles)].slice(-20),future:[]}));setHistories(h=>({...h,[style.id]:{past:[...(h[style.id]?.past||[]).slice(-19),clone(style)],future:[]}}));setStyles(current=>{const next=clone(current);reset(next);return next})}else commit(next=>reset(next.filter(s=>s.id===style.id)),style.id);setPreview(null);setNotice(resetScope==='all'?`${targets.length}개 스타일의 ${groupCount}개 그룹, ${valueCount}개 조정값을 초기화했습니다.`:`${style.name}의 ${groupCount}개 그룹, ${valueCount}개 조정값을 초기화했습니다.`);setResetDialog(false);setResetting(false)},0)};
  const internal=useMemo(()=>{if(!style)return null;const details=statusDetails(style.materials),all=style.materials.reduce((s,m)=>s+m.baseCost*m.baseUsage,0), visible=totalMaterialCost(style.materials);const sumType=(rx:RegExp)=>style.materials.filter(m=>m.sources.some(r=>rx.test(r.materialType))).reduce((s,m)=>s+m.baseCost*m.baseUsage,0);return{all,visible,sewing:sumType(/봉제공임/),packing:sumType(/포장공임/),special:style.materials.filter(m=>m.group==='SPECIAL PROCESS (LIST ONLY)').reduce((s,m)=>s+m.baseCost*m.baseUsage,0),details,review:details.filter(d=>d.disposition==='review').length,separate:details.filter(d=>d.disposition==='separate').length,excluded:details.filter(d=>d.disposition==='excluded').length}},[style]);
  const styleGroups=useMemo(()=>style?[...new Set(style.materials.map(m=>m.group))]:[],[style]);
  const shownMaterials=useMemo(()=>style?.materials.filter(m=>scope==='selected'?selected.has(m.id):groupFilter==='all'||m.group===groupFilter)||[],[style,groupFilter,scope,selected]);
  useEffect(()=>{if((scope!=='all'&&scope!=='selected'&&scope!=='group'&&!styleGroups.includes(scope as CbdGroup))||(groupFilter!=='all'&&!styleGroups.includes(groupFilter as CbdGroup)))setStyleGroupState('all')},[scope,groupFilter,styleGroups]);
  const exportStyles=async(list:StyleData[],internalReview=false)=>{const review=list.reduce((n,s)=>n+s.materials.filter(m=>m.group==='NEEDS REVIEW').length,0);if(review&&!confirm(`미분류 항목이 ${review}개 있습니다. 계속 다운로드할까요?`))return;if(internalReview)await downloadInternalExcel(list,list.length===1?`${list[0].name}_Internal_CBD.xlsx`:'Internal_CBD_All_Styles.xlsx');else await downloadBuyerExcel(list,list.length===1?`${list[0].name}_Buyer_CBD.xlsx`:'Buyer_CBD_All_Styles.xlsx')};
  const uploadFob=async(file?:File,error?:string)=>{if(error)return setNotice(`FOB 파일 오류: ${error}`);if(!file)return;try{const rec=await parseFobFile(file);setFobs(rec);setFobFile({name:file.name,size:file.size,lastModified:file.lastModified,parsedCount:rec.length});let matched=0;setStyles(ds=>ds.map(s=>{const next=clone(s),hit=matchFob(s.name,rec);if(hit.record){matched++;next.finalFob=hit.record.fob;next.fobMatch=hit.record.style;next.fobMatchMethod=hit.method;delete next.fobUnmatchedReason}else{delete next.fobMatch;delete next.fobMatchMethod;next.fobUnmatchedReason=hit.reason}return next}));setShowFobMatches(true);setNotice(`${styles.length}개 스타일 중 ${matched}개를 자동 매칭했습니다.`)}catch(error){setNotice(`FOB 파일 오류: ${error instanceof Error?error.message:'파일을 읽지 못했습니다.'}`)}};
  const mappingDialog=mapping&&<MappingDialog value={mapping} onChange={setMapping} onCancel={()=>setMapping(null)} onApply={()=>{if(mapping.columns.item===undefined||((mapping.columns.usage===undefined)&&(mapping.columns.netUsage===undefined))||((mapping.columns.convertedPrice===undefined)&&(mapping.columns.rawPrice===undefined)))return setNotice('Item, Usage(또는 정소요량), 단가(또는 환산단가)는 필수입니다.');const rows=rowsFromSheet(mapping.rows,mapping.columns,mapping.headerRow,{file:mapping.file,sheet:mapping.sheet},settings),audit=buildErpMaterialAudit(rows);const name=displayStyleName(mapping.file)||displayStyleName(mapping.sheet);const materials=aggregate(buyerRowsWithoutHierarchyDuplicates(rows,dict),settings.defaultLoss,dict);const s:StyleData={id:`${mapping.file}:${mapping.sheet}:${Date.now()}`,name,sourceFile:mapping.file,sourceSheet:mapping.sheet,materials,statusDetails:statusDetails(materials),erpAudit:audit,erpMaterialCost:roundTo4(audit.reduce((sum,row)=>sum+row.includedAmount,0)),laborRemark:'It also includes the listed special process and packing costs in the factory.'};setStyles(ds=>[...ds,s]);setActive(s.id);setMapping(null);setNotice('수동 컬럼 매핑으로 스타일을 분석했습니다.')}}/>;
  if(restoring)return <main className="restoring">마지막 작업을 불러오는 중입니다.</main>;
  if(!styles.length)return <div className="app start-app"><aside><div className="brand small"><span className="brand-mark">CB</span><span className="brand-copy"><b>CBD Manager</b><small>Cost Management</small></span></div><nav className="main-nav" aria-label="주요 메뉴"><span className="nav-label">Workspace</span><button className="active" type="button"><LayoutDashboard size={17}/> BOM Management</button><span className="nav-item disabled"><BarChart3 size={17}/> Style Analysis</span><span className="nav-label">System</span><span className="nav-item disabled"><SettingsIcon size={17}/> Settings</span></nav><div className="sidebar-support"><HelpCircle size={16}/><span><b>Need help?</b><small>Upload an Excel BOM to begin.</small></span></div></aside><main className="workspace start-workspace"><header className="top start-top"><div><span className="eyebrow">BOM Management · Start New Project</span><h1>새 작업 시작</h1><p>Create a costing workspace from your existing BOM file.</p></div></header><div className="start-content"><section className="start-card"><div className="section-heading"><span className="step">01</span><div><h2>Project settings</h2><p>Set the defaults used when the workbook does not provide a value.</p></div></div><div className="settings"><label><span>KRW fallback 환율</span><input type="number" value={settings.exchangeRate} onChange={e=>setSettings({...settings,exchangeRate:+e.target.value})}/><small>KRW per USD</small></label><label><span>기본 CBD 추가 Loss</span><div className="input-suffix"><input type="number" value={settings.defaultLoss*100} onChange={e=>setSettings({...settings,defaultLoss:+e.target.value/100})}/><em>%</em></div><small>Applied to imported materials</small></label></div><div className="section-divider"/><div className="section-heading"><span className="step">02</span><div><h2>BOM Upload</h2><p>Excel parsing and column detection run automatically.</p></div></div><BomUploader onFiles={uploadBom}/>{notice&&<p className="notice">{notice}</p>}<p className="local-help"><span/> 작업은 이 PC의 현재 브라우저에만 자동 저장됩니다.</p></section></div>{mappingDialog}</main></div>;
  const history=histories[style.id]||{past:[],future:[]};
  return <div className="app"><aside><div className="brand small"><span className="brand-mark">CB</span><span className="brand-copy"><b>CBD Manager</b><small>Cost Management</small></span></div><nav className="main-nav" aria-label="주요 메뉴"><span className="nav-label">Workspace</span><button className="active" type="button"><LayoutDashboard size={17}/> BOM Management</button><span className="nav-item current"><BarChart3 size={17}/> Style Analysis</span></nav><div className="side-uploads"><BomUploader compact onFiles={uploadBom}/><FobUploader onFile={uploadFob} fileName={fobFile?.name} summary={fobFile?`${styles.length}개 스타일 중 ${styles.filter(s=>s.fobMatch).length}개 매칭`:undefined}/></div><h3>Styles <em>{styles.length}</em></h3><div className="style-list" ref={styleList} onScroll={e=>setSidebarScrollTop(e.currentTarget.scrollTop)}>{styles.map(s=><button title={s.name} className={`style ${s.id===style?.id?'active':''}`} onClick={()=>setActive(s.id)} key={s.id}><span>{s.name}</span><small>{s.materials.some(m=>m.group==='NEEDS REVIEW')?'검토 필요':'준비됨'}</small></button>)}</div><div className="side-bottom"><button onClick={async()=>{if(!confirm('모든 작업 데이터와 브라우저 자동 저장 내용을 초기화할까요?'))return;suspendSave.current=true;try{await clearSavedWork();setStyles([]);setActive('');setSelections({});setScopes({});setGroupFilters({});setFobs([]);setFobFile(undefined);setHistories({});setSaveStatus('');setNotice('')}catch(error){setNotice(`초기화 실패: ${error instanceof Error?error.message:'브라우저 저장소 오류'}`)}finally{setTimeout(()=>{suspendSave.current=false},700)}}}><X size={15}/> 전체 초기화</button></div></aside>{mappingDialog}
  <section className="workspace"><header className="top"><div className="title-block"><span className="eyebrow">Style Analysis <i>/</i> Cost Dashboard</span><input className="title" aria-label="스타일 이름" value={style.name} onChange={e=>commit(ds=>{ds.find(s=>s.id===style.id)!.name=e.target.value})}/><p><FileSpreadsheet size={13}/>{style.sourceFile} <span>·</span> {style.sourceSheet}</p></div><div className="actions"><div className="history-actions"><button disabled={!history.past.length} onClick={undo}><Undo2 size={16}/> Undo</button><button disabled={!history.future.length} onClick={redo}><Redo2 size={16}/> Redo</button></div><button onClick={()=>exportStyles([style])}><Download size={16}/> Buyer 현재</button><button onClick={()=>exportStyles([style],true)}><Download size={16}/> 내부 현재</button><button onClick={()=>exportStyles(styles)}><Download size={16}/> Buyer 전체</button><button className="primary" onClick={()=>exportStyles(styles,true)}><Download size={16}/> 내부 전체</button></div></header>
  {notice&&<div className="notice bar">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
  <div className="summary">{[['BOM Actual Material',internal?.all],['Buyer-visible Material',internal?.visible],['Difference Embedded',(internal?.visible||0)-(internal?.all||0)],['Internal Sewing',internal?.sewing],['Internal Packing',internal?.packing],['Internal Special Process',internal?.special]].map(([k,v])=><div key={String(k)}><span>{k}</span><b>{money(Number(v))}</b></div>)}<div className={(style.finalFob??Infinity)<(internal?.visible||0)?'danger':''}><span>Final FOB</span><OptionalNumberEditor ariaLabel="Final FOB" className="fob-input" value={style.finalFob} onCommit={value=>commit(ds=>{const current=ds.find(s=>s.id===style.id)!;current.finalFob=value;current.fobMatchMethod='Manual';delete current.fobMatch})}/><small>차액 {style.finalFob===undefined?'—':money(style.finalFob-(internal?.visible||0))}</small></div><div><span>상태</span><div className="status-badges"><button onClick={()=>setStatusView('review')}>검토 {internal?.review}</button><button onClick={()=>setStatusView('separate')}>별도 반영 {internal?.separate}</button><button onClick={()=>setStatusView('excluded')}>제외 {internal?.excluded}</button></div></div></div>
  <section className="internal-review"><header><b>INTERNAL REVIEW</b><span>내부 원가 검토용 · Buyer 파일에는 포함되지 않습니다.</span></header><div>{[['CBD Total Material Cost',money(internal?.visible||0)],['FINAL FOB',style.finalFob===undefined?'—':money(style.finalFob)],['CBD Material / FOB',style.finalFob?`${Math.round((internal?.visible||0)/style.finalFob*100)}%`:'—'],['ERP Pre-cost Material',money(style.erpMaterialCost||0)],['Difference',money((internal?.visible||0)-(style.erpMaterialCost||0))],['Difference Rate',style.erpMaterialCost?`${Math.round(((internal?.visible||0)-(style.erpMaterialCost||0))/style.erpMaterialCost*100)}%`:'—']].map(([label,value])=><p key={label}><span>{label}</span><b>{value}</b>{label==='ERP Pre-cost Material'&&<button onClick={()=>setShowErp(true)}>계산 근거 보기</button>}</p>)}</div></section>
  {fobs.length>0&&!style.fobMatch&&<div className="match"><b>FOB 유사 후보 (자동 확정하지 않음)</b>{fobCandidates(style.name,fobs).map(f=><button onClick={()=>commit(ds=>{const s=ds.find(x=>x.id===style.id)!;s.finalFob=f.fob;s.fobMatch=f.style})}>{f.style} · ${f.fob}</button>)}</div>}
  {statusView&&<StatusDialog title={statusView==='review'?'검토':statusView==='separate'?'별도 반영':'제외'} rows={(internal?.details||[]).filter(d=>d.disposition===statusView)} onClose={()=>setStatusView(null)}/>}
  {showFobMatches&&<FobMatchDialog styles={styles} records={fobs} onClose={()=>setShowFobMatches(false)} onManual={(id,record)=>commit(ds=>{const s=ds.find(x=>x.id===id)!;if(record){s.finalFob=record.fob;s.fobMatch=record.style;s.fobMatchMethod='Manual';delete s.fobUnmatchedReason}else{delete s.fobMatch}},id)}/>}
  {showErp&&<ErpAuditDialog style={style} onClose={()=>setShowErp(false)}/>}
  {resetDialog&&<div className="modal-back"><div className="modal reset-modal" role="dialog" aria-labelledby="adjustment-reset-title"><h2 id="adjustment-reset-title">일괄조정 전체 초기화</h2><p>일괄조정 및 조정값만 원본 기준으로 복원합니다.</p><fieldset><legend>초기화 범위</legend><label><input type="radio" name="reset-scope" checked={resetScope==='current'} onChange={()=>setResetScope('current')}/> 현재 스타일 전체 그룹</label><label><input type="radio" name="reset-scope" checked={resetScope==='all'} onChange={()=>setResetScope('all')}/> 모든 스타일 전체 그룹</label></fieldset><p className="reset-impact">{resetScope==='current'?`${style.name}의 모든 CBD Group에서 조정된 단가, Usage 및 추가 Loss를 원본값으로 복원합니다.`:`현재 등록된 ${styles.length}개 스타일의 모든 일괄조정값을 원본값으로 복원합니다.`}</p><p className="reset-warning">현재 데이터는 일괄조정과 행별 직접 수정을 구분하지 않으므로 모든 숫자 조정값이 Base 값으로 복원됩니다. Remark, CBD Group, Include, FINAL FOB는 유지됩니다.</p><div className="modal-actions"><button disabled={resetting} onClick={()=>setResetDialog(false)}>취소</button><button className="primary" disabled={resetting} onClick={runFullAdjustmentReset}>{resetting?'초기화 중…':'초기화 실행'}</button></div></div></div>}
  <div className="adjustment-reset"><div><b>일괄조정 전체 초기화</b><span>일괄조정 및 조정값만 원본 기준으로 복원합니다.</span></div><button disabled={resetting} title="현재 선택 범위만 초기화하는 조정 방식의 초기화와 달리, 현재 스타일 또는 모든 스타일의 전체 그룹을 복원합니다." onClick={()=>{setResetScope('current');setResetDialog(true)}}><RotateCcw size={15}/> 일괄조정 전체 초기화</button></div>
  <div className="toolbar"><div><b>일괄 조정</b><select aria-label="일괄 조정 대상" value={scope} onChange={e=>setStyleGroupState(e.target.value)}><option value="selected">선택 항목 ({selected.size})</option><option value="all">전체</option><option value="group">선택 그룹</option>{styleGroups.map(g=><option key={g} value={g}>{g}</option>)}</select><select aria-label="일괄 조정 필드" value={target} onChange={e=>setTarget(e.target.value)}><option value="cost">Cost per Unit</option><option value="usage">Usage</option><option value="loss">CBD 추가 Loss</option></select><select aria-label="일괄 조정 방식" value={operation} onChange={e=>setOperation(e.target.value)}><option value="set">값 설정</option><option value="base-percent">원본 대비 % 인상</option><option value="current-percent">현재 값에 % 추가</option><option value="reset">초기화</option></select>{operation!=='reset'&&<NumberEditor ariaLabel="일괄 조정 값" decimals={2} value={bulkValue} onCommit={setBulkValue}/>}<button onClick={()=>setPreview(projected())}>미리보기</button><button className="primary" onClick={()=>{projected(true);setPreview(null)}}>적용</button></div>{preview!==null&&<p>변경 전 {bulkMoney(internal?.visible||0)} → 변경 후 <b>{bulkMoney(preview)}</b></p>}</div>
  <div className="group-filter"><label>CBD Group 보기 <select aria-label="CBD Group 보기" value={groupFilter} onChange={e=>setStyleGroupState(e.target.value)}><option value="all">전체</option>{styleGroups.map(g=><option key={g} value={g}>{g}</option>)}</select></label></div>
  <div className="table-wrap">{scope==='selected'&&!shownMaterials.length?<p className="empty-selection">선택된 자재가 없습니다.</p>:<table><thead><tr><th><input type="checkbox" checked={shownMaterials.length>0&&shownMaterials.every(m=>selected.has(m.id))} onChange={e=>{const next=new Set(selected);shownMaterials.forEach(m=>e.target.checked?next.add(m.id):next.delete(m.id));setSelected(next)}}/></th><th>CBD Group</th><th>Item / Source Structure</th><th>Width</th><th>Unit</th><th>Base Cost</th><th>Adjusted Cost</th><th>Base Usage</th><th>Adjusted Usage</th><th>CBD 추가 Loss</th><th>Extended Cost</th><th>Remark</th><th>Include</th><th></th></tr></thead><tbody>{shownMaterials.map(m=><tr key={m.id} className={!m.included?'excluded':m.group==='NEEDS REVIEW'?'review':''}><td><input type="checkbox" checked={selected.has(m.id)} onChange={e=>{const n=new Set(selected);e.target.checked?n.add(m.id):n.delete(m.id);setSelected(n)}}/></td><td><select value={m.group} onChange={e=>changeGroup(m,e.target.value as CbdGroup)}>{GROUPS.map(g=><option key={g}>{g}</option>)}</select></td><td className="item"><b>{m.item}</b><button className="source" onClick={()=>{const n=new Set(expanded);n.has(m.id)?n.delete(m.id):n.add(m.id);setExpanded(n)}}>{m.sources.length}개 Structure {expanded.has(m.id)?'접기':'보기'}</button>{expanded.has(m.id)&&<ul>{m.sources.map(s=><li key={s.id}>{s.structure}<span>{s.color}</span></li>)}</ul>}</td><td>{m.width}</td><td>{m.unit}</td><td>{m.baseCost.toFixed(4)}</td><td><NumberEditor className={m.adjustedCost!==m.baseCost?'changed':''} value={m.adjustedCost} onCommit={value=>updateMaterial(m.id,{adjustedCost:value})}/></td><td>{m.baseUsage.toFixed(4)}</td><td><NumberEditor className={m.adjustedUsage!==m.baseUsage?'changed':''} value={m.adjustedUsage} onCommit={value=>updateMaterial(m.id,{adjustedUsage:value})}/></td><td><NumberEditor className={m.additionalLoss!==settings.defaultLoss?'changed':''} value={m.additionalLoss*100} onCommit={value=>updateMaterial(m.id,{additionalLoss:value/100})}/>%</td><td><b>{m.group==='SPECIAL PROCESS (LIST ONLY)'?'—':money(extendedCost(m))}</b></td><td><textarea value={m.remark} onChange={e=>updateMaterial(m.id,{remark:e.target.value,remarkEdited:true})}/><button className="source" onClick={()=>updateMaterial(m.id,{remark:m.originalRemark||m.sources.map(s=>s.remark||s.structure).filter(Boolean).join(' / '),remarkEdited:false})}>원본 Remark 복원</button></td><td><input type="checkbox" checked={m.included} onChange={e=>updateMaterial(m.id,{included:e.target.checked})}/></td><td><button title="원본값으로 초기화" onClick={()=>updateMaterial(m.id,{adjustedCost:m.baseCost,adjustedUsage:m.baseUsage,additionalLoss:settings.defaultLoss})}><RotateCcw size={15}/></button>{m.sources.length>1&&<button title="그룹 분리" onClick={()=>commit(ds=>{const s=ds.find(x=>x.id===style.id)!;s.materials=s.materials.flatMap(x=>x.id===m.id?splitMaterial(x):x)})}>분리</button>}</td></tr>)}</tbody></table>}</div>
  <footer><div><b>분류 사전</b><button onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(dict,null,2)],{type:'application/json'}));a.download='cbd-classification-dictionary.json';a.click()}}>JSON 내보내기</button><button onClick={()=>dictInput.current?.click()}>JSON 불러오기</button><input ref={dictInput} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f)setDict(JSON.parse(await f.text()))}}/></div><p>{saveStatus||'자동 저장 대기 중'} · 이 PC의 현재 브라우저에만 저장됩니다.</p></footer></section></div>;
}

function NumberEditor({value,onCommit,className='',decimals=4,ariaLabel}:{value:number;onCommit:(value:number)=>void;className?:string;decimals?:number;ariaLabel?:string}){
  const [draft,setDraft]=useState(value.toFixed(decimals));
  useEffect(()=>setDraft(value.toFixed(decimals)),[value,decimals]);
  const finish=()=>{const next=Number(draft);if(Number.isFinite(next)){setDraft(next.toFixed(decimals));if(next!==value)onCommit(next)}else setDraft(value.toFixed(decimals))};
  return <input aria-label={ariaLabel} className={className} type="number" step=".0001" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={finish} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>;
}

function OptionalNumberEditor({value,onCommit,className='',ariaLabel}:{value?:number;onCommit:(value?:number)=>void;className?:string;ariaLabel?:string}){
  const [draft,setDraft]=useState(value===undefined?'':value.toFixed(4));
  useEffect(()=>setDraft(value===undefined?'':value.toFixed(4)),[value]);
  const finish=()=>{const trimmed=draft.trim();if(!trimmed){setDraft('');if(value!==undefined)onCommit(undefined);return}const next=Number(trimmed);if(Number.isFinite(next)){setDraft(next.toFixed(4));if(next!==value)onCommit(next)}else setDraft(value===undefined?'':value.toFixed(4))};
  return <input aria-label={ariaLabel} className={className} type="text" inputMode="decimal" value={draft} placeholder="-" onChange={e=>setDraft(e.target.value)} onBlur={finish} onWheel={e=>e.currentTarget.blur()} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>;
}

function StatusDialog({title,rows,onClose}:{title:string;rows:RowStatusDetail[];onClose:()=>void}){
  return <div className="modal-back"><div className="modal status-modal"><h2>{title} 상세 ({rows.length})</h2><div className="status-table"><table><thead><tr><th>원본 행</th><th>Item#</th><th>Item</th><th>Structure</th><th>자재구분</th><th>Unit</th><th>환산단가</th><th>자재비용차액대체</th><th>비고</th><th>처리 결과</th><th>사유</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.sourceRow}</td><td>{row.itemNo}</td><td>{row.item}</td><td>{row.structure}</td><td>{row.materialType}</td><td>{row.unit}</td><td>{row.convertedPrice.toFixed(4)}</td><td>{row.materialCostAdjustment.toFixed(4)}</td><td>{row.remark}</td><td>{row.result}</td><td>{row.reason}</td></tr>)}</tbody></table>{!rows.length&&<p>해당 항목이 없습니다.</p>}</div><div className="modal-actions"><button onClick={onClose}>닫기</button></div></div></div>;
}

function FobMatchDialog({styles,records,onClose,onManual}:{styles:StyleData[];records:FobRecord[];onClose:()=>void;onManual:(styleId:string,record?:FobRecord)=>void}){
  return <div className="modal-back"><div className="modal fob-modal"><h2>FOB STYLE 매칭 결과</h2><div className="status-table"><table><thead><tr><th>BOM STYLE</th><th>매칭된 FOB STYLE#</th><th>FINAL FOB</th><th>방식</th><th>미매칭 사유 / 수동 선택</th></tr></thead><tbody>{styles.map(style=><tr key={style.id}><td>{style.name}</td><td>{style.fobMatch||'—'}</td><td>{style.finalFob===undefined?'—':style.finalFob.toFixed(4)}</td><td>{style.fobMatchMethod||'—'}</td><td>{style.fobUnmatchedReason&&<span>{style.fobUnmatchedReason} </span>}<select aria-label={`${style.name} FOB 수동 선택`} value={style.fobMatch||''} onChange={e=>onManual(style.id,records.find(r=>r.style===e.target.value))}><option value="">수동 선택</option>{records.map((record,i)=><option key={`${record.style}:${i}`} value={record.style}>{record.style} · ${record.fob.toFixed(4)}</option>)}</select></td></tr>)}</tbody></table></div><div className="modal-actions"><button onClick={onClose}>닫기</button></div></div></div>;
}

function ErpAuditDialog({style,onClose}:{style:StyleData;onClose:()=>void}){
  const rows=style.erpAudit||[];
  return <div className="modal-back"><div className="modal status-modal"><h2>ERP 사전원가 재료비 계산 근거</h2><p>포함 금액 합계: <b>{money(style.erpMaterialCost||0)}</b> · 포함 {rows.filter(row=>row.included).length}행 / 제외 {rows.filter(row=>!row.included).length}행</p><div className="status-table"><table><thead><tr><th>원본 행</th><th>일련번호</th><th>부모일련번호</th><th>레벨</th><th>하위YN</th><th>자재구분</th><th>Item#</th><th>Item</th><th>금액</th><th>부모행</th><th>포함</th><th>포함 금액</th><th>사유</th></tr></thead><tbody>{rows.map(row=><tr key={row.source.id}><td>{row.source.sourceRow}</td><td>{row.source.serialNo}</td><td>{row.source.parentSerialNo}</td><td>{row.source.level}</td><td>{row.source.hasChildren}</td><td>{row.source.materialType}</td><td>{row.source.itemNo}</td><td>{row.source.item}</td><td>{row.source.amount===undefined?'공란':row.source.amount.toFixed(4)}</td><td>{row.isParent?'Y':'N'}</td><td>{row.included?'Y':'N'}</td><td>{row.includedAmount.toFixed(4)}</td><td>{row.reason}</td></tr>)}</tbody></table></div><div className="modal-actions"><button onClick={onClose}>닫기</button></div></div></div>;
}

function MappingDialog({value,onChange,onApply,onCancel}:{value:{file:string;sheet:string;rows:unknown[][];headerRow:number;columns:ColumnMapping};onChange:(v:any)=>void;onApply:()=>void;onCancel:()=>void}){
  const fields:[string,string][]=[['structure','Structure'],['materialType','자재구분'],['sequence','원순번/순번'],['serialNo','일련번호'],['parentSerialNo','부모일련번호'],['level','레벨'],['hasChildren','하위YN'],['itemNo','Item#'],['item','Item *'],['width','Width'],['color','Color'],['unit','Unit'],['netUsage','정소요량'],['bomLoss','BOM 로스율'],['usage','소요량 *'],['currency','Currency'],['rawPrice','단가'],['convertedPrice','환산단가 *'],['ancillaryCost','부대비용'],['materialCostAdjustment','자재비용차액대체'],['amount','금액'],['specialFlag','특수공정'],['remark','비고']];
  const max=Math.max(1,...value.rows.slice(0,30).map(r=>r.length)); const headers=value.rows[value.headerRow]||[];
  return <div className="modal-back"><div className="modal"><h2>컬럼 매핑</h2><p>{value.file} · {value.sheet} — 자동 인식하지 못한 열을 직접 지정하세요.</p><label>헤더 행 <select value={value.headerRow} onChange={e=>onChange({...value,headerRow:+e.target.value})}>{value.rows.slice(0,30).map((_,i)=><option value={i}>{i+1}행</option>)}</select></label><div className="mapping-grid">{fields.map(([key,label])=><label>{label}<select value={value.columns[key]??''} onChange={e=>onChange({...value,columns:{...value.columns,[key]:e.target.value===''?undefined:+e.target.value}})}><option value="">선택 안 함</option>{Array.from({length:max},(_,i)=><option value={i}>{String.fromCharCode(65+i)} · {String(headers[i]??'')}</option>)}</select></label>)}</div><div className="modal-actions"><button onClick={onCancel}>취소</button><button className="primary" onClick={onApply}>이 매핑으로 분석</button></div></div></div>;
}
