import { describe, expect, it } from 'vitest';
import ExcelJS from 'exceljs';
import { aggregate, detectHeader, rowsFromSheet } from './parser';
import { createBuyerWorkbook } from './exporter';
import type { BomRow, StyleData } from './types';

const settings={exchangeRate:900,defaultLoss:.05};
const row=(id:string,item:string,usage:number,cost:number,structure='BODY',extra:Partial<BomRow>={}):BomRow=>({id,sourceFile:'27 LITE PANT BOM.xls',sourceSheet:'BOM',sourceRow:+id,structure,materialType:'원부자재',sequence:'',itemNo:'',item,width:'',color:'BLACK',unit:'YD',usage,currency:'USD',convertedPrice:cost,rawPrice:cost,specialFlag:'',remark:'',...extra});

describe('BOM parsing and aggregation',()=>{
  it('detects a header within 30 rows regardless of column positions',()=>{const rows=[['title'],[],['Item','Structure','소요량','환산단가','Unit','Width']];const found=detectHeader(rows);expect(found?.row).toBe(2);expect(found?.mapping.item).toBe(0);expect(found?.mapping.usage).toBe(2)});
  it('uses Q usage and U converted price without reapplying BOM loss or KRW conversion',()=>{const rows=[['Structure','자재구분','Item','Unit','정소요량','로스율','소요량','Currency','단가','환산단가'],['A','원부자재','NYLON WEBBING (25M/M)','M',1,20,.5,'KRW',214,.2378],['B','원부자재','CARE LABEL','EA',1,10,1,'KRW',65,.0722]];const found=detectHeader(rows)!;const parsed=rowsFromSheet(rows,found.mapping,found.row,{file:'x.xls',sheet:'BOM'},settings);expect(parsed[0].usage).toBe(.5);expect(parsed[0].convertedPrice).toBe(.2378);expect(parsed[1].convertedPrice).toBe(.0722)});
  it('falls back only when Q/U are absent',()=>{const rows=[['Structure','Item','Unit','정소요량','로스율','Currency','단가'],['A','KRW ITEM','EA',2,10,'KRW',900]];const f=detectHeader(rows)!;const r=rowsFromSheet(rows,f.mapping,f.row,{file:'x',sheet:'s'},settings)[0];expect(r.usage).toBeCloseTo(2.2);expect(r.convertedPrice).toBe(1)});
  it('matches supplied repeated-material validation values and weighted cost',()=>{const rows=[row('1','#7172 STRETCH KEVLAR (WRC0)',.1,21.3),row('2','#7172 STRETCH KEVLAR (WRC0)',.0823,21.3),...Array.from({length:4},(_,i)=>row(`${i+3}`,'ONE MESH (GSM)',.094,2)),row('7','WEBBING POLY 10MM',.1,.0243,'WAIST'),row('8','WEBBING POLY 10MM',.0972,.0241,'BELT')];const m=aggregate(rows,.05,{});const kev=m.find(x=>x.item.startsWith('#7172'))!;expect(kev.sources).toHaveLength(2);expect(kev.baseUsage).toBeCloseTo(.1823);expect(kev.baseCost*kev.baseUsage*1.05).toBeCloseTo(4.0771395);expect(m.find(x=>x.item==='ONE MESH (GSM)')!.baseUsage).toBeCloseTo(.376);const web=m.find(x=>x.item==='WEBBING POLY 10MM')!;expect(web.sources).toHaveLength(2);expect(web.baseUsage).toBeCloseTo(.1972);expect(web.baseCost).toBeCloseTo((.1*.0243+.0972*.0241)/.1972)});
  it('does not merge same material when width or unit differs',()=>{const m=aggregate([row('1','FABRIC',1,2,'A',{width:'50',unit:'YD'}),row('2','FABRIC',1,2,'B',{width:'60',unit:'YD'})],.05,{});expect(m).toHaveLength(2)});
});

describe('Buyer-only workbook',()=>{
  it('blanks thread and special-process detail costs and excludes private source data',async()=>{const mats=aggregate([row('1','THREAD 40S',1,2,'재봉사-A'),row('2','SILICON PRINT COST',1,9,'SECRET STRUCTURE',{materialType:'특수공임',remark:'front logo'}),row('3','FABRIC',1,3,'BODY',{remark:'public'})],.05,{});const style:StyleData={id:'s',name:'27 LITE PANT',sourceFile:'secret BOM.xls',sourceSheet:'정소요량',materials:mats,finalFob:10,laborRemark:'It also includes the listed special process and packing costs in the factory.'};const wb=await createBuyerWorkbook([style],new Date('2025-10-17T00:00:00Z'));const buffer=await wb.xlsx.writeBuffer();const reread=new ExcelJS.Workbook();await reread.xlsx.load(buffer);const ws=reread.worksheets[0];const values=ws.getSheetValues().flat(3).join(' | ');expect(values).not.toContain('SECRET STRUCTURE');expect(values).not.toContain('정소요량');expect(values).not.toContain('secret BOM');const spRow=ws.eachRow.bind(ws);let specialRow=0,threadRow=0;ws.eachRow((r,n)=>{if(r.getCell(2).value==='SILICON PRINT COST')specialRow=n;if(r.getCell(2).value==='THREAD 40S')threadRow=n});for(const n of [specialRow,threadRow])for(let c=5;c<=8;c++)expect(ws.getCell(n,c).value).toBeNull()});
});
